/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend
 * OpenAPI spec version: 1.0.0
 */

export type DeleteApiUsersId200 = {
  message?: string;
};
