/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiUsersId200User } from './getApiUsersId200User';

export type GetApiUsersId200 = {
  message?: string;
  user?: GetApiUsersId200User;
};
