/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend
 * OpenAPI spec version: 1.0.0
 */

export type PostApiAuthRegisterBodyRole = 'photographer' | 'seller' | 'admin' | 'manager';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiAuthRegisterBodyRole = {
  photographer: 'photographer' as PostApiAuthRegisterBodyRole,
  seller: 'seller' as PostApiAuthRegisterBodyRole,
  admin: 'admin' as PostApiAuthRegisterBodyRole,
  manager: 'manager' as PostApiAuthRegisterBodyRole,
};
