/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiUsers201User } from './postApiUsers201User';

export type PostApiUsers201 = {
  user?: PostApiUsers201User;
};
