/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend
 * OpenAPI spec version: 1.0.0
 */

export type PostApiAuthRefresh200 = {
  message?: string;
  /** Новый JWT access token */
  accessToken?: string;
  /** Новый JWT refresh token */
  refreshToken?: string;
};
