/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend
 * OpenAPI spec version: 1.0.0
 */

export type PutApiUsersIdBodyRole = 'photographer' | 'seller' | 'admin' | 'manager';


// eslint-disable-next-line
export const PutApiUsersIdBodyRole = {
  photographer: 'photographer' as PutApiUsersIdBodyRole,
  seller: 'seller' as PutApiUsersIdBodyRole,
  admin: 'admin' as PutApiUsersIdBodyRole,
  manager: 'manager' as PutApiUsersIdBodyRole,
};
