/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiUsersId200User } from './putApiUsersId200User';

export type PutApiUsersId200 = {
  user?: PutApiUsersId200User;
};
