/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend
 * OpenAPI spec version: 1.0.0
 */

/**
 * Роль пользователя
 */
export type UserUpdateRole = 'photographer' | 'seller' | 'admin' | 'manager';


// eslint-disable-next-line
export const UserUpdateRole = {
  photographer: 'photographer' as UserUpdateRole,
  seller: 'seller' as UserUpdateRole,
  admin: 'admin' as UserUpdateRole,
  manager: 'manager' as UserUpdateRole,
};
