/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend
 * OpenAPI spec version: 1.0.0
 */
import type { UserRole } from './userRole';

export interface User {
  /** Имя пользователя */
  username: string;
  /** Email пользователя */
  email: string;
  /** Роль пользователя */
  role?: UserRole;
  /** Уникальный идентификатор */
  id?: string;
  /** JWT access token */
  accessToken?: string;
  /** JWT refresh token */
  refreshToken?: string;
}
