/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend
 * OpenAPI spec version: 1.0.0
 */
import type { UserUpdateRole } from './userUpdateRole';

export interface UserUpdate {
  /** Имя пользователя */
  username?: string;
  /** Email пользователя */
  email?: string;
  /** Роль пользователя */
  role?: UserUpdateRole;
  /** Пароль пользователя */
  password?: string;
}
