/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */

export interface Aimodel {
  /** Уникальный идентификатор AI модели */
  id: string;
  /** Название AI модели */
  title: string;
  /** Описание AI модели */
  description: string;
  /** Дата создания */
  createdAt: string;
  /** Дата последнего обновления */
  updatedAt: string;
}
