/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */

export interface AlbumResponse {
  /** ID альбома */
  id?: string;
  /** Название альбома */
  title?: string;
  /** Описание альбома */
  description?: string;
  /** ID проекта */
  projectId?: string;
  /** Публичный ли альбом */
  isPublic?: boolean;
  /** Ссылка для шаринга */
  shareLink?: string;
  /** ID обложки */
  coverPhotoId?: string;
  /** Теги альбома */
  tags?: string[];
  /** Статус обработки альбома */
  processed?: boolean;
  /** Дата создания */
  createdAt?: string;
  /** Дата обновления */
  updatedAt?: string;
}
