/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export interface AuthError {
  /** Сообщение об ошибке аутентификации */
  message?: string;
  /** HTTP код ошибки */
  statusCode?: number;
  /** Контекст ошибки */
  context?: string;
}
