/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

/**
 * Название (title) генерируется автоматически как следующий чанк: 01, 02, 03 и т.д.
 */
export interface CreateAlbumDto {
  /** ID подпроекта */
  subprojectId: string;
  /** Описание альбома */
  description?: string;
  /** Публичный ли альбом */
  isPublic?: boolean;
  /** Теги альбома */
  tags?: string[];
}
