/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export interface CreatePromptRequest {
  /** Название промпта */
  title: string;
  /** Текст промпта на русском (будет переведён в EN и сохранён в body/default и history[0]) */
  body: string;
}
