/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export interface CreateOrUpdateYandexDiskConfigDto {
  /** OAuth-токен Яндекс.Диска */
  accessToken: string;
  /** Корневая папка на Диске для проекта */
  rootPath: string;
  /** Включена ли загрузка на Диск для проекта */
  isActive?: boolean;
  /** Базовый URL API (по умолчанию https://cloud-api.yandex.net/v1) */
  apiBaseUrl?: string;
  /** Подпись конфига для отображения */
  name?: string;
}
