/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export interface CreateAlbumDto {
  /** Название альбома */
  title: string;
  /** ID подпроекта */
  subprojectId: string;
  /** Описание альбома */
  description?: string;
  /** Публичный ли альбом */
  isPublic?: boolean;
  /** Теги альбома */
  tags?: string[];
}
