/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export interface DeletePhotoResponse {
  /** Статус успешности операции */
  success?: boolean;
  /** Сообщение о результате */
  message?: string;
  /** ID удаленного фото */
  id?: string;
}
