/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */
import type { DescriptorVector } from './descriptorVector';

export interface DescriptorMaskMatchRequest {
  /** Маска лица: 2-10 дескрипторов одного человека в разных ракурсах */
  mask: DescriptorVector[];
  /** Опциональный идентификатор филиала. Если указан — должен входить в workplace пользователя (иначе пустой результат). Если не указан — поиск идёт по всем филиалам из workplace пользователя за сегодня. */
  projectId?: string;
  /** Порог схожести (по умолчанию 0.6) */
  threshold?: number;
  /** Максимальное количество результатов */
  limit?: number;
}
