/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */

/**
 * Массив из 128 чисел, представляющих дескриптор лица
 */
export type DescriptorVector = { values: number[] };
