/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export interface DescriptorMatchItem {
  /** Идентификатор фото */
  photoId?: string;
  /** Расстояние между дескрипторами */
  distance?: number;
}
