/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */
import type { DescriptorVector } from './descriptorVector';

export interface DescriptorMatchRequest {
  /** Список дескрипторов для сравнения */
  descriptors: DescriptorVector[];
  /** Опциональный идентификатор пользователя для ограничения поиска */
  userId?: string;
  /** Опциональный список фото для ограничения поиска */
  photoIds?: string[];
  /** Порог схожести (по умолчанию 0.6) */
  threshold?: number;
  /** Максимальное количество результатов */
  limit?: number;
}
