/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */
import type { DescriptorVector } from './descriptorVector';

export interface DescriptorMaskMatchRequest {
  /** Маска лица: 2-10 дескрипторов одного человека в разных ракурсах */
  mask: DescriptorVector[];
  /** Идентификатор филиала (projectId), в котором производится поиск. Должен входить в workplace пользователя, иначе возврат пустого результата. */
  projectId: string;
  /** Порог схожести (по умолчанию 0.6) */
  threshold?: number;
  /** Максимальное количество результатов */
  limit?: number;
}
