/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */

export type GetCameras200Item = {
  id?: string;
  cameraId?: string;
  projectId?: string;
  isActive?: boolean;
  /** Генерируется автоматически при создании */
  ftpUsername?: string;
  /** Генерируется автоматически при создании */
  ftpPassword?: string;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
};
