/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export interface ImprovementCustomResponse {
  /** Сообщение о результате */
  message?: string;
  /** ID фотографии */
  photoid?: string;
  /** Пользовательский промпт */
  userprompt?: string;
}
