/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */

export interface ImprovePhotosRequest {
  /** Массив ID фотографий для улучшения */
  photoIds: string[];
  /** Массив ID промптов для улучшения. Все промпты будут склеены через запятую в один промпт. */
  promptIds: string[];
}
