/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */

export interface ImprovePhotosRequest {
  /** Массив ID фотографий для улучшения */
  photoIds: string[];
  /** Массив ID промптов для улучшения (опционально). Все промпты будут склеены через точку. Может быть пустым, если указан customPromptText. */
  promptIds?: string[];
  /** Произвольный текст промпта для улучшения (опционально). Будет склеен с промптами из promptIds через точку. Может быть указан один, без promptIds. */
  customPromptText?: string;
}
