/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */
import type { PaginationResponseDataItem } from './paginationResponseDataItem';
import type { PaginationResponsePagination } from './paginationResponsePagination';

export interface PaginationResponse {
  data?: PaginationResponseDataItem[];
  pagination?: PaginationResponsePagination;
}
