/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export type PaginationResponsePagination = {
  /** Текущая страница */
  page?: number;
  /** Количество элементов на странице */
  limit?: number;
  /** Общее количество элементов */
  total?: number;
  /** Общее количество страниц */
  pages?: number;
};
