/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */

export interface Photo {
  /** Уникальный идентификатор фото */
  id: string;
  /** ID альбома, к которому принадлежит фото */
  albumId: string;
  /** URL файла в S3 хранилище */
  fileUrl: string;
  /** Оригинальное имя файла */
  fileName: string;
  /** Размер файла в байтах */
  fileSize: number;
  /** MIME тип файла */
  mimeType: string;
  /** Является ли фото обложкой альбома */
  isCover: boolean;
  /** Теги фото */
  tags: string[];
  /** Дата создания */
  createdAt: string;
  /** Дата последнего обновления */
  updatedAt: string;
}
