/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */
import type { PhotoVersions } from './photoVersions';
import type { PhotoProcessingEntry } from './photoProcessingEntry';

export interface Photo {
  /** Уникальный идентификатор фото */
  id: string;
  /** ID альбома, к которому принадлежит фото */
  albumId: string;
  /** Текущие версии фото (могут изменяться при улучшении) */
  current?: PhotoVersions;
  /** Версии по умолчанию (неизменны, для отката) */
  default: PhotoVersions;
  /** Оригинальное имя файла */
  fileName: string;
  /** Размер файла в байтах */
  fileSize: number;
  /** MIME тип файла */
  mimeType: string;
  /** Является ли фото обложкой альбома */
  isCover: boolean;
  /** Теги фото */
  tags: string[];
  /** Оценка от нейросети (текстовая) */
  rating?: string;
  /** Относительный путь файла на Яндекс.Диске (для перезаписи при реверте) */
  yadisk?: string | null;
  /** Журнал успешных обработок для отчётов по затратам */
  processing?: PhotoProcessingEntry[];
  /** Дата создания */
  createdAt: string;
  /** Дата последнего обновления */
  updatedAt: string;
}
