/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */
import type { PhotoVersions } from './photoVersions';
import type { PhotoProcessingEntry } from './photoProcessingEntry';
import type { PhotoStatus } from './photoStatus';
import type { PhotoStatusOperation } from './photoStatusOperation';

export interface Photo {
  /** Уникальный идентификатор фото */
  id: string;
  /** ID альбома, к которому принадлежит фото */
  albumId: string;
  /** Текущие версии фото (могут изменяться при улучшении) */
  current?: PhotoVersions;
  /** Версии по умолчанию (неизменны, для отката) */
  default: PhotoVersions;
  /** Оригинальное имя файла */
  fileName: string;
  /** Размер файла в байтах */
  fileSize: number;
  /** MIME тип файла */
  mimeType: string;
  /** Является ли фото обложкой альбома */
  isCover: boolean;
  /** Теги фото */
  tags: string[];
  /** Оценка от нейросети (текстовая) */
  rating?: string;
  /** Относительный путь файла на Яндекс.Диске (для перезаписи при реверте) */
  yadisk?: string | null;
  /** Относительный путь обработанной current-версии на Яндекс.Диске */
  yadiskCurrent?: string | null;
  /** Флаг: фото создано из папки "Готовый продукт" при обратной синхронизации */
  readyManaged?: boolean;
  /** Исходный путь файла на Яндекс.Диске внутри папки "Готовый продукт" */
  readySourcePath?: string | null;
  /** Отпечаток источника ready-файла для идемпотентного sync */
  readySourceFingerprint?: string | null;
  /** Журнал успешных обработок для отчётов по затратам */
  processing?: PhotoProcessingEntry[];
  /** Статус обработки фото (improve/addlayer) для polling-индикации */
  status: PhotoStatus;
  /** Какая операция запущена / упала последней */
  statusOperation?: PhotoStatusOperation;
  /** Номер текущей попытки Bull (1..3) — для индикатора «попытка 2/3» */
  statusAttempt?: number | null;
  /** Код причины фейла: E005 — копирайт/safety, STALE — таймаут воркера, UNKNOWN — прочее */
  statusErrorCode?: string | null;
  /** Короткое сообщение об ошибке (детальная отладка — в логах/Replicate Dashboard) */
  statusErrorMessage?: string | null;
  /** Момент последней смены статуса */
  statusUpdatedAt?: string;
  /** Дата создания */
  createdAt: string;
  /** Дата последнего обновления */
  updatedAt: string;
}
