/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */

export interface PhotoVersions {
  /** URL оригинального файла */
  original: string;
  /** URL preview версии (WebP 5-8%) */
  preview: string;
  /** URL маленькой версии (для альбома) */
  small: string;
}
