/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

/**
 * Одна успешная обработка (нейросеть); cost — снимок в USD на момент записи
 */
export interface PhotoProcessingEntry {
  /** Идентификатор модели Replicate */
  model: string;
  at: string;
  cost: number;
  currency: string;
}
