/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export type PostCameras201 = {
  id?: string;
  /** Генерируется автоматически при создании */
  cameraId?: string;
  projectId?: string;
  isActive?: boolean;
  /** Генерируется автоматически при создании */
  ftpUsername?: string;
  /** Генерируется автоматически при создании */
  ftpPassword?: string;
  /** Порт FTP-сервера для настройки подключения на камере (из env FTP_PORT) */
  ftpPort?: string;
  /** URL/host для PASV-режима для настройки на камере (из env PASV_URL) */
  pasvUrl?: string;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
};
