/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export type PostYandexdiskSyncProjectProjectId200 = {
  projectId?: string;
  processed?: number;
  created?: number;
  updated?: number;
  deleted?: number;
  renamed?: number;
  skipped?: number;
  failed?: number;
  errors?: string[];
};
