/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export type PostPhotosUploadBody = {
  /** Файл изображения (только image/*) */
  photo: Blob;
  /** ID альбома для загрузки фото */
  albumId: string;
  /** Теги через запятую (опционально) */
  tags?: string;
};
