/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export type PostPhotosImprove200 = {
  message?: string;
  /** ID фото, реально поставленных в очередь */
  photoIds?: string[];
  /** ID не найденных в БД фото (тихо пропущены) */
  skipped?: string[];
};
