/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectDtoAlbumsItem } from './projectDtoAlbumsItem';

export interface ProjectDto {
  /** ID проекта */
  id?: string;
  /** Название проекта */
  name?: string;
  /** Список альбомов проекта (пока не реализован) */
  albums?: ProjectDtoAlbumsItem[];
}
