/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectCreationRolesErrorRequiredRolesItem } from './projectCreationRolesErrorRequiredRolesItem';

export interface ProjectCreationRolesError {
  /** Сообщение об ошибке прав доступа */
  error: string;
  /** Роли, необходимые для создания проектов */
  requiredRoles: ProjectCreationRolesErrorRequiredRolesItem[];
}
