/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */

export type ProjectCreationRolesErrorRequiredRolesItem = 'admin' | 'owner' | 'agency' | 'cluster';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectCreationRolesErrorRequiredRolesItem = {
  admin: 'admin' as ProjectCreationRolesErrorRequiredRolesItem,
  owner: 'owner' as ProjectCreationRolesErrorRequiredRolesItem,
  agency: 'agency' as ProjectCreationRolesErrorRequiredRolesItem,
  cluster: 'cluster' as ProjectCreationRolesErrorRequiredRolesItem,
};
