/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export interface PromptHistoryEntry {
  /** Версия/метка версии промпта */
  promptVersion: string;
  /** Английский текст после сохранения (для моделей). При новой версии без ru можно передать русский сюда — бэкенд переведёт и перезапишет EN */
  promptBody?: string;
  /** Русский текст версии. При update: если версия уже есть в БД, можно не передавать — сохранятся ru и promptBody из БД */
  ru?: string;
  /** Описание версии */
  description: string;
  /** Оценка версии (число) */
  rate: number;
}
