/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */
import type { PromptHistoryItem } from './promptHistoryItem';

export interface Prompt {
  /** Уникальный идентификатор промпта */
  id: string;
  /** Название промпта */
  title: string;
  /** Текущий текст промпта на английском (для моделей); ввод с фронта при создании/редактировании — на русском, перевод выполняет бэкенд */
  body: string;
  /** Исходный промпт на английском (неизменяемый после создания) */
  default: string;
  /** Версии промпта: сохранённые пользователями лучшие варианты */
  history?: PromptHistoryItem[];
  /** Дата создания */
  createdAt: string;
  /** Дата последнего обновления */
  updatedAt: string;
}
