/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */

export interface PromptResponse {
  /** Уникальный идентификатор промпта */
  id?: string;
  /** Название промпта */
  title?: string;
  /** Текст промпта */
  body?: string;
  /** Исходный промпт */
  default?: string;
  /** Дата создания */
  createdAt?: string;
  /** Дата последнего обновления */
  updatedAt?: string;
}
