/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export type PromptResponseHistoryItem = {
  /** Версия/метка версии промпта */
  promptVersion: string;
  /** Текст этой версии промпта */
  promptBody: string;
  /** Описание версии */
  description: string;
  /** Оценка версии (число) */
  rate: number;
};
