/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export type RegisterResponseRolesItem = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker' | 'prompt' | 'remote';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterResponseRolesItem = {
  admin: 'admin' as RegisterResponseRolesItem,
  owner: 'owner' as RegisterResponseRolesItem,
  agency: 'agency' as RegisterResponseRolesItem,
  cluster: 'cluster' as RegisterResponseRolesItem,
  supervisor: 'supervisor' as RegisterResponseRolesItem,
  maker: 'maker' as RegisterResponseRolesItem,
  prompt: 'prompt' as RegisterResponseRolesItem,
  remote: 'remote' as RegisterResponseRolesItem,
};
