/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */

/**
 * Роль пользователя
 */
export type RegisterResponseRole = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterResponseRole = {
  admin: 'admin' as RegisterResponseRole,
  owner: 'owner' as RegisterResponseRole,
  agency: 'agency' as RegisterResponseRole,
  cluster: 'cluster' as RegisterResponseRole,
  supervisor: 'supervisor' as RegisterResponseRole,
  maker: 'maker' as RegisterResponseRole,
};
