/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */

/**
 * Роль пользователя
 */
export type RegisterResponseRole = 'seller' | 'photographer' | 'manager' | 'admin';


// eslint-disable-next-line
export const RegisterResponseRole = {
  seller: 'seller' as RegisterResponseRole,
  photographer: 'photographer' as RegisterResponseRole,
  manager: 'manager' as RegisterResponseRole,
  admin: 'admin' as RegisterResponseRole,
};
