/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export type RolesErrorAllowedRolesItem = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RolesErrorAllowedRolesItem = {
  admin: 'admin' as RolesErrorAllowedRolesItem,
  owner: 'owner' as RolesErrorAllowedRolesItem,
  agency: 'agency' as RolesErrorAllowedRolesItem,
  cluster: 'cluster' as RolesErrorAllowedRolesItem,
  supervisor: 'supervisor' as RolesErrorAllowedRolesItem,
  maker: 'maker' as RolesErrorAllowedRolesItem,
};
