/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export type RolesErrorRequiredRolesItem = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RolesErrorRequiredRolesItem = {
  admin: 'admin' as RolesErrorRequiredRolesItem,
  owner: 'owner' as RolesErrorRequiredRolesItem,
  agency: 'agency' as RolesErrorRequiredRolesItem,
  cluster: 'cluster' as RolesErrorRequiredRolesItem,
  supervisor: 'supervisor' as RolesErrorRequiredRolesItem,
  maker: 'maker' as RolesErrorRequiredRolesItem,
};
