/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export type RolesErrorCurrentRolesItem = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker' | 'prompt' | 'remote';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RolesErrorCurrentRolesItem = {
  admin: 'admin' as RolesErrorCurrentRolesItem,
  owner: 'owner' as RolesErrorCurrentRolesItem,
  agency: 'agency' as RolesErrorCurrentRolesItem,
  cluster: 'cluster' as RolesErrorCurrentRolesItem,
  supervisor: 'supervisor' as RolesErrorCurrentRolesItem,
  maker: 'maker' as RolesErrorCurrentRolesItem,
  prompt: 'prompt' as RolesErrorCurrentRolesItem,
  remote: 'remote' as RolesErrorCurrentRolesItem,
};
