/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */

/**
 * Целевая роль для операции
 */
export type RolesErrorTargetRole = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RolesErrorTargetRole = {
  admin: 'admin' as RolesErrorTargetRole,
  owner: 'owner' as RolesErrorTargetRole,
  agency: 'agency' as RolesErrorTargetRole,
  cluster: 'cluster' as RolesErrorTargetRole,
  supervisor: 'supervisor' as RolesErrorTargetRole,
  maker: 'maker' as RolesErrorTargetRole,
};
