/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export type RolesErrorTargetRolesItem = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker' | 'prompt' | 'remote';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RolesErrorTargetRolesItem = {
  admin: 'admin' as RolesErrorTargetRolesItem,
  owner: 'owner' as RolesErrorTargetRolesItem,
  agency: 'agency' as RolesErrorTargetRolesItem,
  cluster: 'cluster' as RolesErrorTargetRolesItem,
  supervisor: 'supervisor' as RolesErrorTargetRolesItem,
  maker: 'maker' as RolesErrorTargetRolesItem,
  prompt: 'prompt' as RolesErrorTargetRolesItem,
  remote: 'remote' as RolesErrorTargetRolesItem,
};
