/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

/**
 * Текущая роль пользователя
 */
export type RolesErrorCurrentRole = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RolesErrorCurrentRole = {
  admin: 'admin' as RolesErrorCurrentRole,
  owner: 'owner' as RolesErrorCurrentRole,
  agency: 'agency' as RolesErrorCurrentRole,
  cluster: 'cluster' as RolesErrorCurrentRole,
  supervisor: 'supervisor' as RolesErrorCurrentRole,
  maker: 'maker' as RolesErrorCurrentRole,
};
