/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */
import type { RolesErrorCurrentRole } from './rolesErrorCurrentRole';
import type { RolesErrorTargetRole } from './rolesErrorTargetRole';
import type { RolesErrorAllowedRolesItem } from './rolesErrorAllowedRolesItem';
import type { RolesErrorRequiredRolesItem } from './rolesErrorRequiredRolesItem';

export interface RolesError {
  /** Сообщение об ошибке прав доступа */
  error: string;
  /** Текущая роль пользователя */
  currentRole?: RolesErrorCurrentRole;
  /** Целевая роль для операции */
  targetRole?: RolesErrorTargetRole;
  /** Роли, которые может создавать текущий пользователь */
  allowedRoles?: RolesErrorAllowedRolesItem[];
  /** Роли, необходимые для выполнения операции */
  requiredRoles?: RolesErrorRequiredRolesItem[];
}
