/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export interface SubprojectPreviewDto {
  /** ID подпроекта */
  id?: string;
  /** Название подпроекта */
  name?: string;
  /** ID родительского проекта */
  projectId?: string;
}
