/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */
import type { SuccessResponseData } from './successResponseData';

export interface SuccessResponse {
  /** Сообщение об успехе */
  message?: string;
  /** Данные ответа */
  data?: SuccessResponseData;
}
