/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */
import type { SuccessResponseData } from './successResponseData';

export interface SuccessResponse {
  /** Сообщение об успехе */
  message?: string;
  /** Данные ответа */
  data?: SuccessResponseData;
}
