/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateAlbumDto {
  /** Название альбома */
  title?: string;
  /** Описание альбома */
  description?: string;
  /** Публичный ли альбом */
  isPublic?: boolean;
  /** ID обложки */
  coverPhotoId?: string;
  /** Теги альбома */
  tags?: string[];
}
