/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export interface UpdatePhotoRequest {
  /** Новое имя файла */
  fileName?: string;
  /** Новые теги */
  tags?: string[];
  /** Установить как обложку альбома */
  isCover?: boolean;
}
