/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateResponse {
  /** ID обновленного пользователя */
  id?: string;
  /** Email пользователя */
  email?: string;
  /** Имя пользователя */
  name?: string;
  /** Роль пользователя */
  role?: string;
  /** Активен ли пользователь */
  isActive?: boolean;
}
