/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export type UpdateResponseRolesItem = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker' | 'prompt' | 'remote';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateResponseRolesItem = {
  admin: 'admin' as UpdateResponseRolesItem,
  owner: 'owner' as UpdateResponseRolesItem,
  agency: 'agency' as UpdateResponseRolesItem,
  cluster: 'cluster' as UpdateResponseRolesItem,
  supervisor: 'supervisor' as UpdateResponseRolesItem,
  maker: 'maker' as UpdateResponseRolesItem,
  prompt: 'prompt' as UpdateResponseRolesItem,
  remote: 'remote' as UpdateResponseRolesItem,
};
