/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateResponse {
  /** ID обновленного пользователя */
  id?: string;
  /** Email пользователя */
  email?: string;
  /** Имя пользователя */
  name?: string;
  /** Роль пользователя */
  role?: string;
  /** Активен ли пользователь */
  isActive?: boolean;
}
