/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateAlbumDto {
  /** Название альбома */
  title?: string;
  /** Описание альбома */
  description?: string;
  /** Публичный ли альбом */
  isPublic?: boolean;
  /** ID обложки */
  coverPhotoId?: string;
  /** Теги альбома */
  tags?: string[];
  /** Массив photoId из папки "Готовый продукт" */
  readyProducts?: string[];
}
