/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */
import type { PhotoVersions } from './photoVersions';

export interface UploadPhotoResponse {
  /** ID созданного фото */
  id?: string;
  /** ID альбома */
  albumId?: string;
  /** Текущие версии фото */
  current?: PhotoVersions;
  /** Версии по умолчанию */
  default?: PhotoVersions;
  /** Имя файла */
  fileName?: string;
  /** Размер файла в байтах */
  fileSize?: number;
  /** MIME тип */
  mimeType?: string;
  /** Является ли обложкой */
  isCover?: boolean;
  /** Теги */
  tags?: string[];
  /** Дата создания */
  createdAt?: string;
  /** Дата обновления */
  updatedAt?: string;
}
