/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */
import type { PhotoVersions } from './photoVersions';

export interface UploadPhotoResponse {
  /** ID созданного фото */
  id?: string;
  /** ID альбома */
  albumId?: string;
  /** Текущие версии фото */
  current?: PhotoVersions;
  /** Версии по умолчанию */
  default?: PhotoVersions;
  /** Имя файла */
  fileName?: string;
  /** Размер файла в байтах */
  fileSize?: number;
  /** MIME тип */
  mimeType?: string;
  /** Является ли обложкой */
  isCover?: boolean;
  /** Теги */
  tags?: string[];
  /** Оценка от нейросети (текстовая) */
  rating?: string;
  /** Относительный путь файла на Яндекс.Диске */
  yadisk?: string | null;
  /** Относительный путь обработанной current-версии на Яндекс.Диске */
  yadiskCurrent?: string | null;
  /** Флаг: фото создано из папки "Готовый продукт" при обратной синхронизации */
  readyManaged?: boolean;
  /** Исходный путь файла на Яндекс.Диске внутри папки "Готовый продукт" */
  readySourcePath?: string | null;
  /** Отпечаток источника ready-файла для идемпотентного sync */
  readySourceFingerprint?: string | null;
  /** Дата создания */
  createdAt?: string;
  /** Дата обновления */
  updatedAt?: string;
}
