/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */

export interface UploadPhotoRequest {
  /** Файл изображения (только image/*) */
  photo: Blob;
  /** ID альбома для загрузки фото */
  albumId: string;
  /** Теги через запятую (опционально) */
  tags?: string;
}
