/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export type UserCreationRolesErrorAllowedRolesItem = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserCreationRolesErrorAllowedRolesItem = {
  admin: 'admin' as UserCreationRolesErrorAllowedRolesItem,
  owner: 'owner' as UserCreationRolesErrorAllowedRolesItem,
  agency: 'agency' as UserCreationRolesErrorAllowedRolesItem,
  cluster: 'cluster' as UserCreationRolesErrorAllowedRolesItem,
  supervisor: 'supervisor' as UserCreationRolesErrorAllowedRolesItem,
  maker: 'maker' as UserCreationRolesErrorAllowedRolesItem,
};
