/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */
import type { UserRole } from './userRole';

export interface User {
  /** Уникальный идентификатор пользователя */
  id?: string;
  /** Email пользователя */
  email: string;
  /** Имя пользователя */
  name: string;
  /** Роль пользователя */
  role?: UserRole;
  /** Активен ли пользователь */
  isActive?: boolean;
  /** Массив идентификаторов проектов, в которых участвует пользователь */
  workplace?: string[];
}
