/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export type UserResponseRolesItem = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker' | 'prompt' | 'remote';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserResponseRolesItem = {
  admin: 'admin' as UserResponseRolesItem,
  owner: 'owner' as UserResponseRolesItem,
  agency: 'agency' as UserResponseRolesItem,
  cluster: 'cluster' as UserResponseRolesItem,
  supervisor: 'supervisor' as UserResponseRolesItem,
  maker: 'maker' as UserResponseRolesItem,
  prompt: 'prompt' as UserResponseRolesItem,
  remote: 'remote' as UserResponseRolesItem,
};
