/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export type UserRegisterDtoRolesItem = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker' | 'prompt' | 'remote';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRegisterDtoRolesItem = {
  admin: 'admin' as UserRegisterDtoRolesItem,
  owner: 'owner' as UserRegisterDtoRolesItem,
  agency: 'agency' as UserRegisterDtoRolesItem,
  cluster: 'cluster' as UserRegisterDtoRolesItem,
  supervisor: 'supervisor' as UserRegisterDtoRolesItem,
  maker: 'maker' as UserRegisterDtoRolesItem,
  prompt: 'prompt' as UserRegisterDtoRolesItem,
  remote: 'remote' as UserRegisterDtoRolesItem,
};
