/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */
import type { UserInfoResponseRole } from './userInfoResponseRole';

export interface UserInfoResponse {
  /** Уникальный идентификатор пользователя */
  id?: string;
  /** Email пользователя */
  email?: string;
  /** Имя пользователя */
  name?: string;
  /** Роль пользователя */
  role?: UserInfoResponseRole;
  /** Массив идентификаторов проектов, в которых участвует пользователь */
  workplace?: string[];
}
