/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */
import type { UserUpdateRolesErrorCurrentRole } from './userUpdateRolesErrorCurrentRole';
import type { UserUpdateRolesErrorTargetRole } from './userUpdateRolesErrorTargetRole';
import type { UserUpdateRolesErrorAllowedRolesItem } from './userUpdateRolesErrorAllowedRolesItem';

export interface UserUpdateRolesError {
  /** Сообщение об ошибке прав доступа */
  error: string;
  /** Текущая роль пользователя */
  currentRole: UserUpdateRolesErrorCurrentRole;
  /** Целевая роль для обновления */
  targetRole?: UserUpdateRolesErrorTargetRole;
  /** Роли, которые может обновлять текущий пользователь */
  allowedRoles?: UserUpdateRolesErrorAllowedRolesItem[];
}
