/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export type UserUpdateRolesErrorTargetRolesItem = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker' | 'prompt' | 'remote';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserUpdateRolesErrorTargetRolesItem = {
  admin: 'admin' as UserUpdateRolesErrorTargetRolesItem,
  owner: 'owner' as UserUpdateRolesErrorTargetRolesItem,
  agency: 'agency' as UserUpdateRolesErrorTargetRolesItem,
  cluster: 'cluster' as UserUpdateRolesErrorTargetRolesItem,
  supervisor: 'supervisor' as UserUpdateRolesErrorTargetRolesItem,
  maker: 'maker' as UserUpdateRolesErrorTargetRolesItem,
  prompt: 'prompt' as UserUpdateRolesErrorTargetRolesItem,
  remote: 'remote' as UserUpdateRolesErrorTargetRolesItem,
};
