/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */
import type { UserCreationRolesErrorCurrentRolesItem } from './userCreationRolesErrorCurrentRolesItem';
import type { UserCreationRolesErrorTargetRolesItem } from './userCreationRolesErrorTargetRolesItem';
import type { UserCreationRolesErrorAllowedRolesItem } from './userCreationRolesErrorAllowedRolesItem';

export interface UserCreationRolesError {
  /** Сообщение об ошибке прав доступа */
  error: string;
  /** Роли текущего пользователя */
  currentRoles: UserCreationRolesErrorCurrentRolesItem[];
  /** Целевые роли для создания */
  targetRoles: UserCreationRolesErrorTargetRolesItem[];
  /** Роли, которые может назначать текущий пользователь */
  allowedRoles: UserCreationRolesErrorAllowedRolesItem[];
}
