/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */

export type UserUpdateRolesErrorAllowedRolesItem = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserUpdateRolesErrorAllowedRolesItem = {
  admin: 'admin' as UserUpdateRolesErrorAllowedRolesItem,
  owner: 'owner' as UserUpdateRolesErrorAllowedRolesItem,
  agency: 'agency' as UserUpdateRolesErrorAllowedRolesItem,
  cluster: 'cluster' as UserUpdateRolesErrorAllowedRolesItem,
  supervisor: 'supervisor' as UserUpdateRolesErrorAllowedRolesItem,
  maker: 'maker' as UserUpdateRolesErrorAllowedRolesItem,
};
