/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */

/**
 * Новая роль пользователя
 */
export type UserUpdateDtoRole = 'seller' | 'photographer' | 'manager' | 'admin';


// eslint-disable-next-line
export const UserUpdateDtoRole = {
  seller: 'seller' as UserUpdateDtoRole,
  photographer: 'photographer' as UserUpdateDtoRole,
  manager: 'manager' as UserUpdateDtoRole,
  admin: 'admin' as UserUpdateDtoRole,
};
