/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */
import type { UserDeleteErrorCurrentRolesItem } from './userDeleteErrorCurrentRolesItem';
import type { UserDeleteErrorTargetRolesItem } from './userDeleteErrorTargetRolesItem';

export interface UserDeleteError {
  /** Описание ошибки */
  error?: string;
  /** ID пользователя */
  userId?: string;
  /** Роли текущего пользователя */
  currentRoles?: UserDeleteErrorCurrentRolesItem[];
  /** Роли пользователя для удаления */
  targetRoles?: UserDeleteErrorTargetRolesItem[];
}
