/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export interface UserDeleteError {
  /** Описание ошибки */
  error?: string;
  /** ID пользователя */
  userId?: string;
  /** Роль текущего пользователя */
  currentRole?: string;
  /** Роль пользователя для удаления */
  targetRole?: string;
}
