/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

/**
 * Роль пользователя
 */
export type UserRegisterDtoRole = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRegisterDtoRole = {
  admin: 'admin' as UserRegisterDtoRole,
  owner: 'owner' as UserRegisterDtoRole,
  agency: 'agency' as UserRegisterDtoRole,
  cluster: 'cluster' as UserRegisterDtoRole,
  supervisor: 'supervisor' as UserRegisterDtoRole,
  maker: 'maker' as UserRegisterDtoRole,
};
