/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

/**
 * Новая роль пользователя
 */
export type UserUpdateDtoRole = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserUpdateDtoRole = {
  admin: 'admin' as UserUpdateDtoRole,
  owner: 'owner' as UserUpdateDtoRole,
  agency: 'agency' as UserUpdateDtoRole,
  cluster: 'cluster' as UserUpdateDtoRole,
  supervisor: 'supervisor' as UserUpdateDtoRole,
  maker: 'maker' as UserUpdateDtoRole,
};
