/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */

/**
 * Роль пользователя
 */
export type UserRegisterDtoRole = 'seller' | 'photographer' | 'manager' | 'admin';


// eslint-disable-next-line
export const UserRegisterDtoRole = {
  seller: 'seller' as UserRegisterDtoRole,
  photographer: 'photographer' as UserRegisterDtoRole,
  manager: 'manager' as UserRegisterDtoRole,
  admin: 'admin' as UserRegisterDtoRole,
};
