/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

/**
 * Целевая роль для создания
 */
export type UserCreationRolesErrorTargetRole = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserCreationRolesErrorTargetRole = {
  admin: 'admin' as UserCreationRolesErrorTargetRole,
  owner: 'owner' as UserCreationRolesErrorTargetRole,
  agency: 'agency' as UserCreationRolesErrorTargetRole,
  cluster: 'cluster' as UserCreationRolesErrorTargetRole,
  supervisor: 'supervisor' as UserCreationRolesErrorTargetRole,
  maker: 'maker' as UserCreationRolesErrorTargetRole,
};
