/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */
import type { UserRolesItem } from './userRolesItem';

export interface User {
  /** Уникальный идентификатор пользователя */
  id?: string;
  /** Email пользователя */
  email: string;
  /** Имя пользователя */
  name: string;
  /** Массив ролей пользователя. Должен содержать хотя бы одну иерархическую роль
(admin, owner, agency, cluster, supervisor, maker). Capability-роли (prompt, remote)
выдаются дополнительно и доступны только для назначения ролями admin/owner.
 */
  roles?: UserRolesItem[];
  /** Активен ли пользователь */
  isActive?: boolean;
  /** Массив идентификаторов проектов, в которых участвует пользователь */
  workplace?: string[];
}
