/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export type UserDeleteErrorTargetRolesItem = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker' | 'prompt' | 'remote';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserDeleteErrorTargetRolesItem = {
  admin: 'admin' as UserDeleteErrorTargetRolesItem,
  owner: 'owner' as UserDeleteErrorTargetRolesItem,
  agency: 'agency' as UserDeleteErrorTargetRolesItem,
  cluster: 'cluster' as UserDeleteErrorTargetRolesItem,
  supervisor: 'supervisor' as UserDeleteErrorTargetRolesItem,
  maker: 'maker' as UserDeleteErrorTargetRolesItem,
  prompt: 'prompt' as UserDeleteErrorTargetRolesItem,
  remote: 'remote' as UserDeleteErrorTargetRolesItem,
};
