/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export type UserCreationRolesErrorTargetRolesItem = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker' | 'prompt' | 'remote';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserCreationRolesErrorTargetRolesItem = {
  admin: 'admin' as UserCreationRolesErrorTargetRolesItem,
  owner: 'owner' as UserCreationRolesErrorTargetRolesItem,
  agency: 'agency' as UserCreationRolesErrorTargetRolesItem,
  cluster: 'cluster' as UserCreationRolesErrorTargetRolesItem,
  supervisor: 'supervisor' as UserCreationRolesErrorTargetRolesItem,
  maker: 'maker' as UserCreationRolesErrorTargetRolesItem,
  prompt: 'prompt' as UserCreationRolesErrorTargetRolesItem,
  remote: 'remote' as UserCreationRolesErrorTargetRolesItem,
};
