/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

/**
 * Роль пользователя
 */
export type UserRole = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRole = {
  admin: 'admin' as UserRole,
  owner: 'owner' as UserRole,
  agency: 'agency' as UserRole,
  cluster: 'cluster' as UserRole,
  supervisor: 'supervisor' as UserRole,
  maker: 'maker' as UserRole,
};
