/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */
import type { UserCreationRolesErrorCurrentRole } from './userCreationRolesErrorCurrentRole';
import type { UserCreationRolesErrorTargetRole } from './userCreationRolesErrorTargetRole';
import type { UserCreationRolesErrorAllowedRolesItem } from './userCreationRolesErrorAllowedRolesItem';

export interface UserCreationRolesError {
  /** Сообщение об ошибке прав доступа */
  error: string;
  /** Текущая роль пользователя */
  currentRole: UserCreationRolesErrorCurrentRole;
  /** Целевая роль для создания */
  targetRole: UserCreationRolesErrorTargetRole;
  /** Роли, которые может создавать текущий пользователь */
  allowedRoles: UserCreationRolesErrorAllowedRolesItem[];
}
