/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export type UserInfoResponseRolesItem = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker' | 'prompt' | 'remote';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserInfoResponseRolesItem = {
  admin: 'admin' as UserInfoResponseRolesItem,
  owner: 'owner' as UserInfoResponseRolesItem,
  agency: 'agency' as UserInfoResponseRolesItem,
  cluster: 'cluster' as UserInfoResponseRolesItem,
  supervisor: 'supervisor' as UserInfoResponseRolesItem,
  maker: 'maker' as UserInfoResponseRolesItem,
  prompt: 'prompt' as UserInfoResponseRolesItem,
  remote: 'remote' as UserInfoResponseRolesItem,
};
