/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */
import type { UserRegisterDtoRole } from './userRegisterDtoRole';

export interface UserRegisterDto {
  /** Email пользователя */
  email: string;
  /** Имя пользователя */
  name: string;
  /** Пароль пользователя */
  password: string;
  /** Роль пользователя */
  role?: UserRegisterDtoRole;
  /** Массив идентификаторов проектов, в которых участвует пользователь */
  workplace?: string[];
}
