/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */
import type { UserRegisterDtoRolesItem } from './userRegisterDtoRolesItem';

export interface UserRegisterDto {
  /** Email пользователя */
  email: string;
  /** Имя пользователя */
  name: string;
  /** Пароль пользователя */
  password: string;
  /** Массив ролей. По умолчанию ["maker"]. Capability-роли (prompt, remote) могут выдавать только admin/owner. */
  roles?: UserRegisterDtoRolesItem[];
  /** Массив идентификаторов проектов, в которых участвует пользователь */
  workplace?: string[];
}
