/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */
import type { UserUpdateDtoRole } from './userUpdateDtoRole';

export interface UserUpdateDto {
  /** ID пользователя для обновления */
  id?: string;
  /** Новый email пользователя */
  email?: string;
  /** Новое имя пользователя */
  name?: string;
  /** Новый пароль пользователя */
  password?: string;
  /** Новая роль пользователя */
  role?: UserUpdateDtoRole;
  /** Массив идентификаторов проектов, в которых участвует пользователь */
  workplace?: string[];
  /** Статус активности пользователя */
  isActive?: boolean;
}
