/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

/**
 * Целевая роль для обновления
 */
export type UserUpdateRolesErrorTargetRole = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserUpdateRolesErrorTargetRole = {
  admin: 'admin' as UserUpdateRolesErrorTargetRole,
  owner: 'owner' as UserUpdateRolesErrorTargetRole,
  agency: 'agency' as UserUpdateRolesErrorTargetRole,
  cluster: 'cluster' as UserUpdateRolesErrorTargetRole,
  supervisor: 'supervisor' as UserUpdateRolesErrorTargetRole,
  maker: 'maker' as UserUpdateRolesErrorTargetRole,
};
