/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export type UserUpdateRolesErrorCurrentRolesItem = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker' | 'prompt' | 'remote';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserUpdateRolesErrorCurrentRolesItem = {
  admin: 'admin' as UserUpdateRolesErrorCurrentRolesItem,
  owner: 'owner' as UserUpdateRolesErrorCurrentRolesItem,
  agency: 'agency' as UserUpdateRolesErrorCurrentRolesItem,
  cluster: 'cluster' as UserUpdateRolesErrorCurrentRolesItem,
  supervisor: 'supervisor' as UserUpdateRolesErrorCurrentRolesItem,
  maker: 'maker' as UserUpdateRolesErrorCurrentRolesItem,
  prompt: 'prompt' as UserUpdateRolesErrorCurrentRolesItem,
  remote: 'remote' as UserUpdateRolesErrorCurrentRolesItem,
};
