/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */

export interface UserUpdateDto {
  /** Новое имя пользователя */
  name?: string;
  /** Новый пароль пользователя */
  password?: string;
}
