/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */
import type { UserUpdateRolesErrorCurrentRolesItem } from './userUpdateRolesErrorCurrentRolesItem';
import type { UserUpdateRolesErrorTargetRolesItem } from './userUpdateRolesErrorTargetRolesItem';
import type { UserUpdateRolesErrorAllowedRolesItem } from './userUpdateRolesErrorAllowedRolesItem';

export interface UserUpdateRolesError {
  /** Сообщение об ошибке прав доступа */
  error: string;
  /** Роли текущего пользователя */
  currentRoles: UserUpdateRolesErrorCurrentRolesItem[];
  /** Целевые роли для обновления */
  targetRoles?: UserUpdateRolesErrorTargetRolesItem[];
  /** Роли, которые может назначать текущий пользователь */
  allowedRoles?: UserUpdateRolesErrorAllowedRolesItem[];
}
