/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export type UserDeleteErrorCurrentRolesItem = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker' | 'prompt' | 'remote';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserDeleteErrorCurrentRolesItem = {
  admin: 'admin' as UserDeleteErrorCurrentRolesItem,
  owner: 'owner' as UserDeleteErrorCurrentRolesItem,
  agency: 'agency' as UserDeleteErrorCurrentRolesItem,
  cluster: 'cluster' as UserDeleteErrorCurrentRolesItem,
  supervisor: 'supervisor' as UserDeleteErrorCurrentRolesItem,
  maker: 'maker' as UserDeleteErrorCurrentRolesItem,
  prompt: 'prompt' as UserDeleteErrorCurrentRolesItem,
  remote: 'remote' as UserDeleteErrorCurrentRolesItem,
};
