/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */

/**
 * Роль пользователя
 */
export type UserInfoResponseRole = 'seller' | 'photographer' | 'manager' | 'admin';


// eslint-disable-next-line
export const UserInfoResponseRole = {
  seller: 'seller' as UserInfoResponseRole,
  photographer: 'photographer' as UserInfoResponseRole,
  manager: 'manager' as UserInfoResponseRole,
  admin: 'admin' as UserInfoResponseRole,
};
