/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export type UserCreationRolesErrorCurrentRolesItem = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker' | 'prompt' | 'remote';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserCreationRolesErrorCurrentRolesItem = {
  admin: 'admin' as UserCreationRolesErrorCurrentRolesItem,
  owner: 'owner' as UserCreationRolesErrorCurrentRolesItem,
  agency: 'agency' as UserCreationRolesErrorCurrentRolesItem,
  cluster: 'cluster' as UserCreationRolesErrorCurrentRolesItem,
  supervisor: 'supervisor' as UserCreationRolesErrorCurrentRolesItem,
  maker: 'maker' as UserCreationRolesErrorCurrentRolesItem,
  prompt: 'prompt' as UserCreationRolesErrorCurrentRolesItem,
  remote: 'remote' as UserCreationRolesErrorCurrentRolesItem,
};
