/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

export type UserUpdateDtoRolesItem = 'admin' | 'owner' | 'agency' | 'cluster' | 'supervisor' | 'maker' | 'prompt' | 'remote';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserUpdateDtoRolesItem = {
  admin: 'admin' as UserUpdateDtoRolesItem,
  owner: 'owner' as UserUpdateDtoRolesItem,
  agency: 'agency' as UserUpdateDtoRolesItem,
  cluster: 'cluster' as UserUpdateDtoRolesItem,
  supervisor: 'supervisor' as UserUpdateDtoRolesItem,
  maker: 'maker' as UserUpdateDtoRolesItem,
  prompt: 'prompt' as UserUpdateDtoRolesItem,
  remote: 'remote' as UserUpdateDtoRolesItem,
};
