/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */
import type { ValidationErrorResponseDetailsItemTarget } from './validationErrorResponseDetailsItemTarget';
import type { ValidationErrorResponseDetailsItemConstraints } from './validationErrorResponseDetailsItemConstraints';

export type ValidationErrorResponseDetailsItem = {
  /** Объект с ошибками валидации */
  target?: ValidationErrorResponseDetailsItemTarget;
  /** Поле с ошибкой */
  property?: string;
  /** Значение поля */
  value?: string;
  /** Ограничения валидации */
  constraints?: ValidationErrorResponseDetailsItemConstraints;
};
