/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */

/**
 * Конфиг Яндекс.Диска (токен в ответе маскируется)
 */
export interface YandexDiskConfigResponse {
  /** ID записи конфига */
  id?: string;
  /** ID проекта */
  projectId?: string;
  /** Токен маскирован (xxxx***yyyy) */
  accessToken?: string;
  /** Корневая папка на Диске */
  rootPath?: string;
  /** Включена ли загрузка */
  isActive?: boolean;
  /** Базовый URL API */
  apiBaseUrl?: string;
  /** Подпись конфига */
  name?: string;
  createdAt?: string;
  updatedAt?: string;
}
