/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend - платформа для фотографов
 * OpenAPI spec version: 1.0.0
 */
import axios,{
  AxiosRequestConfig,
  AxiosResponse,
  AxiosError
} from 'axios'
import {
  useQuery,
  useMutation,
  UseQueryOptions,
  UseMutationOptions,
  QueryFunction,
  MutationFunction,
  UseQueryResult,
  QueryKey
} from 'react-query'
import type {
  LoginResponse,
  AuthError,
  ErrorResponse,
  UserLoginDto,
  RegisterResponse,
  UserRegisterDto,
  UpdateResponse,
  UserUpdateDto,
  UserInfoResponse,
  ProjectResponse,
  CreateProjectDto,
  GetAllProjectsResponse,
  ProjectDto,
  UpdateProjectDto,
  DeleteProjectsDelete200,
  DeleteProjectDto,
  AlbumResponse,
  AlbumErrorResponse,
  SearchAlbumsByTagsDto,
  SetCoverPhotoDto,
  AddTagDto,
  RemoveTagDto,
  CreateAlbumDto,
  UpdateAlbumDto,
  AlbumDeleteResponse,
  UploadPhotoResponse,
  PhotoErrorResponse,
  PostPhotosUploadBody,
  Photo,
  UpdatePhotoRequest,
  DeletePhotoResponse,
  PhotoListResponse,
  SetCoverRequest
} from './model'

// eslint-disable-next-line
type AsyncReturnType<
T extends (...args: any) => Promise<any>
> = T extends (...args: any) => Promise<infer R> ? R : any;


/**
 * Аутентификация пользователя по email и паролю
 * @summary Вход в систему
 */
export const postUsersLogin = (
    userLoginDto: UserLoginDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LoginResponse>> => {
    return axios.post(
      `/users/login`,
      userLoginDto,options
    );
  }



    export const usePostUsersLogin = <TError = AxiosError<AuthError | ErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postUsersLogin>, TError,{data: UserLoginDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postUsersLogin>, {data: UserLoginDto}> = (props) => {
          const {data} = props || {};

          return  postUsersLogin(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postUsersLogin>, TError, {data: UserLoginDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Создание нового аккаунта пользователя
 * @summary Регистрация нового пользователя
 */
export const postUsersRegister = (
    userRegisterDto: UserRegisterDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RegisterResponse>> => {
    return axios.post(
      `/users/register`,
      userRegisterDto,options
    );
  }



    export const usePostUsersRegister = <TError = AxiosError<ErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postUsersRegister>, TError,{data: UserRegisterDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postUsersRegister>, {data: UserRegisterDto}> = (props) => {
          const {data} = props || {};

          return  postUsersRegister(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postUsersRegister>, TError, {data: UserRegisterDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Обновление информации о пользователе (требует аутентификации)
 * @summary Обновление данных пользователя
 */
export const putUsersUpdate = (
    userUpdateDto: UserUpdateDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UpdateResponse>> => {
    return axios.put(
      `/users/update`,
      userUpdateDto,options
    );
  }



    export const usePutUsersUpdate = <TError = AxiosError<AuthError | ErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof putUsersUpdate>, TError,{data: UserUpdateDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof putUsersUpdate>, {data: UserUpdateDto}> = (props) => {
          const {data} = props || {};

          return  putUsersUpdate(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof putUsersUpdate>, TError, {data: UserUpdateDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Возвращает информацию о авторизованном пользователе
 * @summary Получение информации о текущем пользователе
 */
export const getUsersInfo = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserInfoResponse>> => {
    return axios.get(
      `/users/info`,options
    );
  }


export const getGetUsersInfoQueryKey = () => [`/users/info`];

    
export const useGetUsersInfo = <TData = AsyncReturnType<typeof getUsersInfo>, TError = AxiosError<AuthError>>(
  options?: { query?:UseQueryOptions<AsyncReturnType<typeof getUsersInfo>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetUsersInfoQueryKey();

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getUsersInfo>> = () => getUsersInfo(axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getUsersInfo>, TError, TData>(queryKey, queryFn, queryOptions)

  return {
    queryKey,
    ...query
  }
}


/**
 * Создание нового проекта с указанным названием
 * @summary Создание нового проекта
 */
export const postProjectsCreate = (
    createProjectDto: CreateProjectDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProjectResponse>> => {
    return axios.post(
      `/projects/create`,
      createProjectDto,options
    );
  }



    export const usePostProjectsCreate = <TError = AxiosError<ErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postProjectsCreate>, TError,{data: CreateProjectDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postProjectsCreate>, {data: CreateProjectDto}> = (props) => {
          const {data} = props || {};

          return  postProjectsCreate(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postProjectsCreate>, TError, {data: CreateProjectDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Возвращает список всех проектов
 * @summary Получение всех проектов
 */
export const getProjects = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetAllProjectsResponse>> => {
    return axios.get(
      `/projects`,options
    );
  }


export const getGetProjectsQueryKey = () => [`/projects`];

    
export const useGetProjects = <TData = AsyncReturnType<typeof getProjects>, TError = AxiosError<ErrorResponse>>(
  options?: { query?:UseQueryOptions<AsyncReturnType<typeof getProjects>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetProjectsQueryKey();

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getProjects>> = () => getProjects(axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getProjects>, TError, TData>(queryKey, queryFn, queryOptions)

  return {
    queryKey,
    ...query
  }
}


/**
 * Возвращает информацию о проекте по его идентификатору
 * @summary Получение проекта по ID
 */
export const getProjectsId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProjectDto>> => {
    return axios.get(
      `/projects/${id}`,options
    );
  }


export const getGetProjectsIdQueryKey = (id: string,) => [`/projects/${id}`];

    
export const useGetProjectsId = <TData = AsyncReturnType<typeof getProjectsId>, TError = AxiosError<ErrorResponse>>(
 id: string, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getProjectsId>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetProjectsIdQueryKey(id);

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getProjectsId>> = () => getProjectsId(id, axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getProjectsId>, TError, TData>(queryKey, queryFn, {enabled: !!(id), ...queryOptions})

  return {
    queryKey,
    ...query
  }
}


/**
 * Обновление названия существующего проекта
 * @summary Обновление проекта
 */
export const putProjectsUpdate = (
    updateProjectDto: UpdateProjectDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProjectResponse>> => {
    return axios.put(
      `/projects/update`,
      updateProjectDto,options
    );
  }



    export const usePutProjectsUpdate = <TError = AxiosError<ErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof putProjectsUpdate>, TError,{data: UpdateProjectDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof putProjectsUpdate>, {data: UpdateProjectDto}> = (props) => {
          const {data} = props || {};

          return  putProjectsUpdate(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof putProjectsUpdate>, TError, {data: UpdateProjectDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Удаление проекта по его идентификатору
 * @summary Удаление проекта
 */
export const deleteProjectsDelete = (
    deleteProjectDto: DeleteProjectDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeleteProjectsDelete200>> => {
    return axios.delete(
      `/projects/delete`,{data:
      deleteProjectDto, ...options}
    );
  }



    export const useDeleteProjectsDelete = <TError = AxiosError<ErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof deleteProjectsDelete>, TError,{data: DeleteProjectDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof deleteProjectsDelete>, {data: DeleteProjectDto}> = (props) => {
          const {data} = props || {};

          return  deleteProjectsDelete(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof deleteProjectsDelete>, TError, {data: DeleteProjectDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Получение списка всех публичных альбомов (не требует аутентификации)
 * @summary Получение публичных альбомов
 */
export const getAlbumsPublic = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumResponse[]>> => {
    return axios.get(
      `/albums/public`,options
    );
  }


export const getGetAlbumsPublicQueryKey = () => [`/albums/public`];

    
export const useGetAlbumsPublic = <TData = AsyncReturnType<typeof getAlbumsPublic>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<AsyncReturnType<typeof getAlbumsPublic>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetAlbumsPublicQueryKey();

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getAlbumsPublic>> = () => getAlbumsPublic(axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getAlbumsPublic>, TError, TData>(queryKey, queryFn, queryOptions)

  return {
    queryKey,
    ...query
  }
}


/**
 * Получение всех альбомов, принадлежащих конкретному проекту (требует аутентификации)
 * @summary Получение альбомов проекта
 */
export const getAlbumsProjectProjectId = (
    projectId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumResponse[]>> => {
    return axios.get(
      `/albums/project/${projectId}`,options
    );
  }


export const getGetAlbumsProjectProjectIdQueryKey = (projectId: string,) => [`/albums/project/${projectId}`];

    
export const useGetAlbumsProjectProjectId = <TData = AsyncReturnType<typeof getAlbumsProjectProjectId>, TError = AxiosError<AlbumErrorResponse>>(
 projectId: string, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getAlbumsProjectProjectId>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetAlbumsProjectProjectIdQueryKey(projectId);

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getAlbumsProjectProjectId>> = () => getAlbumsProjectProjectId(projectId, axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getAlbumsProjectProjectId>, TError, TData>(queryKey, queryFn, {enabled: !!(projectId), ...queryOptions})

  return {
    queryKey,
    ...query
  }
}


/**
 * Получение публичного альбома по ссылке для шаринга (не требует аутентификации)
 * @summary Получение альбома по ссылке для шаринга
 */
export const getAlbumsShareShareLink = (
    shareLink: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumResponse>> => {
    return axios.get(
      `/albums/share/${shareLink}`,options
    );
  }


export const getGetAlbumsShareShareLinkQueryKey = (shareLink: string,) => [`/albums/share/${shareLink}`];

    
export const useGetAlbumsShareShareLink = <TData = AsyncReturnType<typeof getAlbumsShareShareLink>, TError = AxiosError<AlbumErrorResponse>>(
 shareLink: string, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getAlbumsShareShareLink>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetAlbumsShareShareLinkQueryKey(shareLink);

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getAlbumsShareShareLink>> = () => getAlbumsShareShareLink(shareLink, axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getAlbumsShareShareLink>, TError, TData>(queryKey, queryFn, {enabled: !!(shareLink), ...queryOptions})

  return {
    queryKey,
    ...query
  }
}


/**
 * Поиск альбомов по указанным тегам (требует аутентификации)
 * @summary Поиск альбомов по тегам
 */
export const postAlbumsSearchTags = (
    searchAlbumsByTagsDto: SearchAlbumsByTagsDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumResponse[]>> => {
    return axios.post(
      `/albums/search/tags`,
      searchAlbumsByTagsDto,options
    );
  }



    export const usePostAlbumsSearchTags = <TError = AxiosError<AlbumErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postAlbumsSearchTags>, TError,{data: SearchAlbumsByTagsDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postAlbumsSearchTags>, {data: SearchAlbumsByTagsDto}> = (props) => {
          const {data} = props || {};

          return  postAlbumsSearchTags(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postAlbumsSearchTags>, TError, {data: SearchAlbumsByTagsDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Установка фотографии в качестве обложки альбома (требует аутентификации)
 * @summary Установка обложки альбома
 */
export const putAlbumsCover = (
    setCoverPhotoDto: SetCoverPhotoDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumResponse>> => {
    return axios.put(
      `/albums/cover`,
      setCoverPhotoDto,options
    );
  }



    export const usePutAlbumsCover = <TError = AxiosError<AlbumErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof putAlbumsCover>, TError,{data: SetCoverPhotoDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof putAlbumsCover>, {data: SetCoverPhotoDto}> = (props) => {
          const {data} = props || {};

          return  putAlbumsCover(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof putAlbumsCover>, TError, {data: SetCoverPhotoDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Добавление нового тега к альбому (требует аутентификации)
 * @summary Добавление тега к альбому
 */
export const postAlbumsTag = (
    addTagDto: AddTagDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumResponse>> => {
    return axios.post(
      `/albums/tag`,
      addTagDto,options
    );
  }



    export const usePostAlbumsTag = <TError = AxiosError<AlbumErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postAlbumsTag>, TError,{data: AddTagDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postAlbumsTag>, {data: AddTagDto}> = (props) => {
          const {data} = props || {};

          return  postAlbumsTag(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postAlbumsTag>, TError, {data: AddTagDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Удаление тега из альбома (требует аутентификации)
 * @summary Удаление тега из альбома
 */
export const deleteAlbumsTag = (
    removeTagDto: RemoveTagDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumResponse>> => {
    return axios.delete(
      `/albums/tag`,{data:
      removeTagDto, ...options}
    );
  }



    export const useDeleteAlbumsTag = <TError = AxiosError<AlbumErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof deleteAlbumsTag>, TError,{data: RemoveTagDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof deleteAlbumsTag>, {data: RemoveTagDto}> = (props) => {
          const {data} = props || {};

          return  deleteAlbumsTag(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof deleteAlbumsTag>, TError, {data: RemoveTagDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Создание нового альбома для проекта (требует аутентификации)
 * @summary Создание нового альбома
 */
export const postAlbums = (
    createAlbumDto: CreateAlbumDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumResponse>> => {
    return axios.post(
      `/albums`,
      createAlbumDto,options
    );
  }



    export const usePostAlbums = <TError = AxiosError<AlbumErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postAlbums>, TError,{data: CreateAlbumDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postAlbums>, {data: CreateAlbumDto}> = (props) => {
          const {data} = props || {};

          return  postAlbums(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postAlbums>, TError, {data: CreateAlbumDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Получение списка всех альбомов пользователя (требует аутентификации)
 * @summary Получение всех альбомов
 */
export const getAlbums = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumResponse[]>> => {
    return axios.get(
      `/albums`,options
    );
  }


export const getGetAlbumsQueryKey = () => [`/albums`];

    
export const useGetAlbums = <TData = AsyncReturnType<typeof getAlbums>, TError = AxiosError<AlbumErrorResponse>>(
  options?: { query?:UseQueryOptions<AsyncReturnType<typeof getAlbums>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetAlbumsQueryKey();

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getAlbums>> = () => getAlbums(axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getAlbums>, TError, TData>(queryKey, queryFn, queryOptions)

  return {
    queryKey,
    ...query
  }
}


/**
 * Получение информации об альбоме по его идентификатору (требует аутентификации)
 * @summary Получение альбома по ID
 */
export const getAlbumsId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumResponse>> => {
    return axios.get(
      `/albums/${id}`,options
    );
  }


export const getGetAlbumsIdQueryKey = (id: string,) => [`/albums/${id}`];

    
export const useGetAlbumsId = <TData = AsyncReturnType<typeof getAlbumsId>, TError = AxiosError<AlbumErrorResponse>>(
 id: string, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getAlbumsId>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetAlbumsIdQueryKey(id);

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getAlbumsId>> = () => getAlbumsId(id, axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getAlbumsId>, TError, TData>(queryKey, queryFn, {enabled: !!(id), ...queryOptions})

  return {
    queryKey,
    ...query
  }
}


/**
 * Обновление информации об альбоме (требует аутентификации)
 * @summary Обновление альбома
 */
export const putAlbumsId = (
    id: string,
    updateAlbumDto: UpdateAlbumDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumResponse>> => {
    return axios.put(
      `/albums/${id}`,
      updateAlbumDto,options
    );
  }



    export const usePutAlbumsId = <TError = AxiosError<AlbumErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof putAlbumsId>, TError,{id: string;data: UpdateAlbumDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof putAlbumsId>, {id: string;data: UpdateAlbumDto}> = (props) => {
          const {id,data} = props || {};

          return  putAlbumsId(id,data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof putAlbumsId>, TError, {id: string;data: UpdateAlbumDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Удаление альбома по его идентификатору (требует аутентификации)
 * @summary Удаление альбома
 */
export const deleteAlbumsId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumDeleteResponse>> => {
    return axios.delete(
      `/albums/${id}`,options
    );
  }



    export const useDeleteAlbumsId = <TError = AxiosError<AlbumErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof deleteAlbumsId>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof deleteAlbumsId>, {id: string}> = (props) => {
          const {id} = props || {};

          return  deleteAlbumsId(id,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof deleteAlbumsId>, TError, {id: string}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Загружает изображение в S3 хранилище и создает запись в базе данных
 * @summary Загрузка фото в альбом
 */
export const postPhotosUpload = (
    postPhotosUploadBody: PostPhotosUploadBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UploadPhotoResponse>> => {const formData = new FormData();
formData.append('photo', postPhotosUploadBody.photo)
formData.append('albumId', postPhotosUploadBody.albumId)
if(postPhotosUploadBody.tags !== undefined) {
 formData.append('tags', postPhotosUploadBody.tags)
 }

    return axios.post(
      `/photos/upload`,
      formData,options
    );
  }



    export const usePostPhotosUpload = <TError = AxiosError<PhotoErrorResponse | void>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postPhotosUpload>, TError,{data: PostPhotosUploadBody}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postPhotosUpload>, {data: PostPhotosUploadBody}> = (props) => {
          const {data} = props || {};

          return  postPhotosUpload(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postPhotosUpload>, TError, {data: PostPhotosUploadBody}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Возвращает информацию о фото по его уникальному идентификатору
 * @summary Получение фото по ID
 */
export const getPhotosId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Photo>> => {
    return axios.get(
      `/photos/${id}`,options
    );
  }


export const getGetPhotosIdQueryKey = (id: string,) => [`/photos/${id}`];

    
export const useGetPhotosId = <TData = AsyncReturnType<typeof getPhotosId>, TError = AxiosError<void | PhotoErrorResponse>>(
 id: string, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getPhotosId>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetPhotosIdQueryKey(id);

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getPhotosId>> = () => getPhotosId(id, axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getPhotosId>, TError, TData>(queryKey, queryFn, {enabled: !!(id), ...queryOptions})

  return {
    queryKey,
    ...query
  }
}


/**
 * Обновляет метаданные фото (имя файла, теги, статус обложки)
 * @summary Обновление метаданных фото
 */
export const putPhotosId = (
    id: string,
    updatePhotoRequest: UpdatePhotoRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Photo>> => {
    return axios.put(
      `/photos/${id}`,
      updatePhotoRequest,options
    );
  }



    export const usePutPhotosId = <TError = AxiosError<PhotoErrorResponse | void>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof putPhotosId>, TError,{id: string;data: UpdatePhotoRequest}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof putPhotosId>, {id: string;data: UpdatePhotoRequest}> = (props) => {
          const {id,data} = props || {};

          return  putPhotosId(id,data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof putPhotosId>, TError, {id: string;data: UpdatePhotoRequest}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Удаляет фото из базы данных и S3 хранилища
 * @summary Удаление фото
 */
export const deletePhotosId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeletePhotoResponse>> => {
    return axios.delete(
      `/photos/${id}`,options
    );
  }



    export const useDeletePhotosId = <TError = AxiosError<void | PhotoErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof deletePhotosId>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof deletePhotosId>, {id: string}> = (props) => {
          const {id} = props || {};

          return  deletePhotosId(id,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof deletePhotosId>, TError, {id: string}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Возвращает список всех фото в указанном альбоме
 * @summary Получение фото альбома
 */
export const getPhotosAlbumAlbumId = (
    albumId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PhotoListResponse>> => {
    return axios.get(
      `/photos/album/${albumId}`,options
    );
  }


export const getGetPhotosAlbumAlbumIdQueryKey = (albumId: string,) => [`/photos/album/${albumId}`];

    
export const useGetPhotosAlbumAlbumId = <TData = AsyncReturnType<typeof getPhotosAlbumAlbumId>, TError = AxiosError<void>>(
 albumId: string, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getPhotosAlbumAlbumId>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetPhotosAlbumAlbumIdQueryKey(albumId);

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getPhotosAlbumAlbumId>> = () => getPhotosAlbumAlbumId(albumId, axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getPhotosAlbumAlbumId>, TError, TData>(queryKey, queryFn, {enabled: !!(albumId), ...queryOptions})

  return {
    queryKey,
    ...query
  }
}


/**
 * Устанавливает указанное фото как обложку альбома
 * @summary Установка обложки альбома
 */
export const putPhotosIdSetcover = (
    id: string,
    setCoverRequest: SetCoverRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Photo>> => {
    return axios.put(
      `/photos/${id}/set-cover`,
      setCoverRequest,options
    );
  }



    export const usePutPhotosIdSetcover = <TError = AxiosError<PhotoErrorResponse | void>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof putPhotosIdSetcover>, TError,{id: string;data: SetCoverRequest}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof putPhotosIdSetcover>, {id: string;data: SetCoverRequest}> = (props) => {
          const {id,data} = props || {};

          return  putPhotosIdSetcover(id,data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof putPhotosIdSetcover>, TError, {id: string;data: SetCoverRequest}, TContext>(mutationFn, mutationOptions)
    }
    
