/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * WanmaX Backend API
 * API документация для WanmaX Backend - Автоматизированный конвейер обработки фотографий
 * OpenAPI spec version: 1.0.0
 */
import axios,{
  AxiosRequestConfig,
  AxiosResponse,
  AxiosError
} from 'axios'
import {
  useQuery,
  useMutation,
  UseQueryOptions,
  UseMutationOptions,
  QueryFunction,
  MutationFunction,
  UseQueryResult,
  QueryKey
} from 'react-query'
import type {
  LoginResponse,
  AuthError,
  ErrorResponse,
  UserLoginDto,
  RegisterResponse,
  UserCreationRolesError,
  UserRegisterDto,
  UpdateResponse,
  UserUpdateRolesError,
  UserUpdateDto,
  UserInfoResponse,
  UserResponse,
  DeleteResponse,
  UserDeleteError,
  UserDeleteDto,
  ProjectResponse,
  ProjectCreationRolesError,
  CreateProjectDto,
  GetAllProjectsResponse,
  ProjectDto,
  UpdateProjectDto,
  DeleteProjectsDelete200,
  DeleteProjectDto,
  SubprojectResponse,
  CreateSubprojectDto,
  GetAllSubprojectsResponse,
  GetSubprojectsParams,
  UpdateSubprojectDto,
  DeleteSubprojects200,
  DeleteSubprojectDto,
  SubprojectDto,
  AlbumResponse,
  AlbumErrorResponse,
  SearchAlbumsByTagsDto,
  SetCoverPhotoDto,
  AddTagDto,
  RemoveTagDto,
  CreateAlbumDto,
  UpdateAlbumDto,
  AlbumDeleteResponse,
  SetProcessedDto,
  UploadPhotoResponse,
  PhotoErrorResponse,
  PostPhotosUploadBody,
  Photo,
  UpdatePhotoRequest,
  DeletePhotoResponse,
  PhotoListResponse,
  SetCoverRequest,
  GetPhotosProcessingusageParams,
  GetPhotosProcessingusageSummaryParams,
  PostPhotosImprovement200,
  PostPhotosImprovementBody,
  PostPhotosImprovementcustom200,
  PostPhotosImprovementcustomBody,
  PostPhotosAddlayer200,
  PostPhotosAddlayerBody,
  RatingPhotoResponse,
  RatingPhotoRequest,
  DescriptorMatchResponse,
  DescriptorMatchRequest,
  DescriptorMaskMatchRequest,
  PromptResponse,
  PromptErrorResponse,
  CreatePromptRequest,
  UpdatePromptRequest,
  AimodelResponse,
  AimodelErrorResponse,
  CreateAimodelRequest,
  PostCameras201,
  PostCamerasBody,
  GetCameras200Item,
  PutCamerasId200,
  PutCamerasIdBody,
  YandexDiskConfigResponse,
  CreateOrUpdateYandexDiskConfigDto,
  YandexDiskDeleteResponse,
  PostYandexdiskSyncProjectProjectId200,
  PutSettingsUsdrubBody
} from './model'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AsyncReturnType<
T extends (...args: any) => Promise<any>
> = T extends (...args: any) => Promise<infer R> ? R : any;


/**
 * Аутентификация пользователя по email и паролю
 * @summary Вход в систему
 */
export const postUsersLogin = (
    userLoginDto: UserLoginDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LoginResponse>> => {
    return axios.post(
      `/users/login`,
      userLoginDto,options
    );
  }



    export const usePostUsersLogin = <TError = AxiosError<AuthError | ErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postUsersLogin>, TError,{data: UserLoginDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postUsersLogin>, {data: UserLoginDto}> = (props) => {
          const {data} = props || {};

          return  postUsersLogin(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postUsersLogin>, TError, {data: UserLoginDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Создание нового аккаунта пользователя
 * @summary Регистрация нового пользователя
 */
export const postUsersRegister = (
    userRegisterDto: UserRegisterDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RegisterResponse>> => {
    return axios.post(
      `/users/register`,
      userRegisterDto,options
    );
  }



    export const usePostUsersRegister = <TError = AxiosError<UserCreationRolesError | ErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postUsersRegister>, TError,{data: UserRegisterDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postUsersRegister>, {data: UserRegisterDto}> = (props) => {
          const {data} = props || {};

          return  postUsersRegister(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postUsersRegister>, TError, {data: UserRegisterDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Обновление информации о пользователе (требует аутентификации)
 * @summary Обновление данных пользователя
 */
export const putUsersUpdate = (
    userUpdateDto: UserUpdateDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UpdateResponse>> => {
    return axios.put(
      `/users/update`,
      userUpdateDto,options
    );
  }



    export const usePutUsersUpdate = <TError = AxiosError<AuthError | UserUpdateRolesError | ErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof putUsersUpdate>, TError,{data: UserUpdateDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof putUsersUpdate>, {data: UserUpdateDto}> = (props) => {
          const {data} = props || {};

          return  putUsersUpdate(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof putUsersUpdate>, TError, {data: UserUpdateDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Возвращает информацию о авторизованном пользователе
 * @summary Получение информации о текущем пользователе
 */
export const getUsersInfo = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserInfoResponse>> => {
    return axios.get(
      `/users/info`,options
    );
  }


export const getGetUsersInfoQueryKey = () => [`/users/info`];

    
export const useGetUsersInfo = <TData = AsyncReturnType<typeof getUsersInfo>, TError = AxiosError<AuthError>>(
  options?: { query?:UseQueryOptions<AsyncReturnType<typeof getUsersInfo>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetUsersInfoQueryKey();

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getUsersInfo>> = () => getUsersInfo(axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getUsersInfo>, TError, TData>(queryKey, queryFn, queryOptions)

  return {
    queryKey,
    ...query
  }
}


/**
 * Возвращает список всех пользователей в системе (требует аутентификации)
 * @summary Получение всех пользователей
 */
export const getUsersAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserResponse[]>> => {
    return axios.get(
      `/users/all`,options
    );
  }


export const getGetUsersAllQueryKey = () => [`/users/all`];

    
export const useGetUsersAll = <TData = AsyncReturnType<typeof getUsersAll>, TError = AxiosError<AuthError>>(
  options?: { query?:UseQueryOptions<AsyncReturnType<typeof getUsersAll>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetUsersAllQueryKey();

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getUsersAll>> = () => getUsersAll(axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getUsersAll>, TError, TData>(queryKey, queryFn, queryOptions)

  return {
    queryKey,
    ...query
  }
}


/**
 * Удаление пользователя из системы. Сам себя удалить нельзя, только вышестоящая роль может удалить нижестоящую.
 * @summary Удаление пользователя
 */
export const deleteUsersDelete = (
    userDeleteDto: UserDeleteDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeleteResponse>> => {
    return axios.delete(
      `/users/delete`,{data:
      userDeleteDto, ...options}
    );
  }



    export const useDeleteUsersDelete = <TError = AxiosError<ErrorResponse | AuthError | UserDeleteError>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof deleteUsersDelete>, TError,{data: UserDeleteDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof deleteUsersDelete>, {data: UserDeleteDto}> = (props) => {
          const {data} = props || {};

          return  deleteUsersDelete(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof deleteUsersDelete>, TError, {data: UserDeleteDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Создание нового проекта с указанным названием
 * @summary Создание нового проекта
 */
export const postProjectsCreate = (
    createProjectDto: CreateProjectDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProjectResponse>> => {
    return axios.post(
      `/projects/create`,
      createProjectDto,options
    );
  }



    export const usePostProjectsCreate = <TError = AxiosError<ProjectCreationRolesError | ErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postProjectsCreate>, TError,{data: CreateProjectDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postProjectsCreate>, {data: CreateProjectDto}> = (props) => {
          const {data} = props || {};

          return  postProjectsCreate(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postProjectsCreate>, TError, {data: CreateProjectDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Возвращает список всех проектов
 * @summary Получение всех проектов
 */
export const getProjects = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetAllProjectsResponse>> => {
    return axios.get(
      `/projects`,options
    );
  }


export const getGetProjectsQueryKey = () => [`/projects`];

    
export const useGetProjects = <TData = AsyncReturnType<typeof getProjects>, TError = AxiosError<ErrorResponse>>(
  options?: { query?:UseQueryOptions<AsyncReturnType<typeof getProjects>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetProjectsQueryKey();

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getProjects>> = () => getProjects(axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getProjects>, TError, TData>(queryKey, queryFn, queryOptions)

  return {
    queryKey,
    ...query
  }
}


/**
 * Возвращает информацию о проекте по его идентификатору
 * @summary Получение проекта по ID
 */
export const getProjectsProjectId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProjectDto>> => {
    return axios.get(
      `/projects/project/${id}`,options
    );
  }


export const getGetProjectsProjectIdQueryKey = (id: string,) => [`/projects/project/${id}`];

    
export const useGetProjectsProjectId = <TData = AsyncReturnType<typeof getProjectsProjectId>, TError = AxiosError<ErrorResponse>>(
 id: string, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getProjectsProjectId>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetProjectsProjectIdQueryKey(id);

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getProjectsProjectId>> = () => getProjectsProjectId(id, axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getProjectsProjectId>, TError, TData>(queryKey, queryFn, {enabled: !!(id), ...queryOptions})

  return {
    queryKey,
    ...query
  }
}


/**
 * Обновление названия существующего проекта
 * @summary Обновление проекта
 */
export const putProjectsUpdate = (
    updateProjectDto: UpdateProjectDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProjectResponse>> => {
    return axios.put(
      `/projects/update`,
      updateProjectDto,options
    );
  }



    export const usePutProjectsUpdate = <TError = AxiosError<ErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof putProjectsUpdate>, TError,{data: UpdateProjectDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof putProjectsUpdate>, {data: UpdateProjectDto}> = (props) => {
          const {data} = props || {};

          return  putProjectsUpdate(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof putProjectsUpdate>, TError, {data: UpdateProjectDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Удаление проекта по его идентификатору
 * @summary Удаление проекта
 */
export const deleteProjectsDelete = (
    deleteProjectDto: DeleteProjectDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeleteProjectsDelete200>> => {
    return axios.delete(
      `/projects/delete`,{data:
      deleteProjectDto, ...options}
    );
  }



    export const useDeleteProjectsDelete = <TError = AxiosError<ErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof deleteProjectsDelete>, TError,{data: DeleteProjectDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof deleteProjectsDelete>, {data: DeleteProjectDto}> = (props) => {
          const {data} = props || {};

          return  deleteProjectsDelete(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof deleteProjectsDelete>, TError, {data: DeleteProjectDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Создание нового подпроекта с указанным названием и ID родительского проекта
 * @summary Создание нового подпроекта
 */
export const postSubprojects = (
    createSubprojectDto: CreateSubprojectDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SubprojectResponse>> => {
    return axios.post(
      `/subprojects`,
      createSubprojectDto,options
    );
  }



    export const usePostSubprojects = <TError = AxiosError<ErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postSubprojects>, TError,{data: CreateSubprojectDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postSubprojects>, {data: CreateSubprojectDto}> = (props) => {
          const {data} = props || {};

          return  postSubprojects(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postSubprojects>, TError, {data: CreateSubprojectDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Возвращает список подпроектов для указанного проекта
 * @summary Получение подпроектов по projectId
 */
export const getSubprojects = (
    params?: GetSubprojectsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetAllSubprojectsResponse>> => {
    return axios.get(
      `/subprojects`,{
        params,
    ...options}
    );
  }


export const getGetSubprojectsQueryKey = (params?: GetSubprojectsParams,) => [`/subprojects`, ...(params ? [params]: [])];

    
export const useGetSubprojects = <TData = AsyncReturnType<typeof getSubprojects>, TError = AxiosError<ErrorResponse>>(
 params?: GetSubprojectsParams, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getSubprojects>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetSubprojectsQueryKey(params);

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getSubprojects>> = () => getSubprojects(params, axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getSubprojects>, TError, TData>(queryKey, queryFn, queryOptions)

  return {
    queryKey,
    ...query
  }
}


/**
 * Обновление названия и ID родительского проекта существующего подпроекта
 * @summary Обновление подпроекта
 */
export const putSubprojects = (
    updateSubprojectDto: UpdateSubprojectDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SubprojectResponse>> => {
    return axios.put(
      `/subprojects`,
      updateSubprojectDto,options
    );
  }



    export const usePutSubprojects = <TError = AxiosError<ErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof putSubprojects>, TError,{data: UpdateSubprojectDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof putSubprojects>, {data: UpdateSubprojectDto}> = (props) => {
          const {data} = props || {};

          return  putSubprojects(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof putSubprojects>, TError, {data: UpdateSubprojectDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Удаление подпроекта по его идентификатору
 * @summary Удаление подпроекта
 */
export const deleteSubprojects = (
    deleteSubprojectDto: DeleteSubprojectDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeleteSubprojects200>> => {
    return axios.delete(
      `/subprojects`,{data:
      deleteSubprojectDto, ...options}
    );
  }



    export const useDeleteSubprojects = <TError = AxiosError<ErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof deleteSubprojects>, TError,{data: DeleteSubprojectDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof deleteSubprojects>, {data: DeleteSubprojectDto}> = (props) => {
          const {data} = props || {};

          return  deleteSubprojects(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof deleteSubprojects>, TError, {data: DeleteSubprojectDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Возвращает информацию о подпроекте по его идентификатору
 * @summary Получение подпроекта по ID
 */
export const getSubprojectsId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SubprojectDto>> => {
    return axios.get(
      `/subprojects/${id}`,options
    );
  }


export const getGetSubprojectsIdQueryKey = (id: string,) => [`/subprojects/${id}`];

    
export const useGetSubprojectsId = <TData = AsyncReturnType<typeof getSubprojectsId>, TError = AxiosError<ErrorResponse>>(
 id: string, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getSubprojectsId>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetSubprojectsIdQueryKey(id);

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getSubprojectsId>> = () => getSubprojectsId(id, axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getSubprojectsId>, TError, TData>(queryKey, queryFn, {enabled: !!(id), ...queryOptions})

  return {
    queryKey,
    ...query
  }
}


/**
 * Получение списка всех публичных альбомов (не требует аутентификации)
 * @summary Получение публичных альбомов
 */
export const getAlbumsPublic = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumResponse[]>> => {
    return axios.get(
      `/albums/public`,options
    );
  }


export const getGetAlbumsPublicQueryKey = () => [`/albums/public`];

    
export const useGetAlbumsPublic = <TData = AsyncReturnType<typeof getAlbumsPublic>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<AsyncReturnType<typeof getAlbumsPublic>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetAlbumsPublicQueryKey();

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getAlbumsPublic>> = () => getAlbumsPublic(axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getAlbumsPublic>, TError, TData>(queryKey, queryFn, queryOptions)

  return {
    queryKey,
    ...query
  }
}


/**
 * Получение всех альбомов, принадлежащих конкретному подпроекту (требует аутентификации)
 * @summary Получение альбомов подпроекта
 */
export const getAlbumsSubprojectSubprojectId = (
    subprojectId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumResponse[]>> => {
    return axios.get(
      `/albums/subproject/${subprojectId}`,options
    );
  }


export const getGetAlbumsSubprojectSubprojectIdQueryKey = (subprojectId: string,) => [`/albums/subproject/${subprojectId}`];

    
export const useGetAlbumsSubprojectSubprojectId = <TData = AsyncReturnType<typeof getAlbumsSubprojectSubprojectId>, TError = AxiosError<AlbumErrorResponse>>(
 subprojectId: string, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getAlbumsSubprojectSubprojectId>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetAlbumsSubprojectSubprojectIdQueryKey(subprojectId);

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getAlbumsSubprojectSubprojectId>> = () => getAlbumsSubprojectSubprojectId(subprojectId, axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getAlbumsSubprojectSubprojectId>, TError, TData>(queryKey, queryFn, {enabled: !!(subprojectId), ...queryOptions})

  return {
    queryKey,
    ...query
  }
}


/**
 * Получение публичного альбома по ссылке для шаринга (не требует аутентификации)
 * @summary Получение альбома по ссылке для шаринга
 */
export const getAlbumsShareShareLink = (
    shareLink: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumResponse>> => {
    return axios.get(
      `/albums/share/${shareLink}`,options
    );
  }


export const getGetAlbumsShareShareLinkQueryKey = (shareLink: string,) => [`/albums/share/${shareLink}`];

    
export const useGetAlbumsShareShareLink = <TData = AsyncReturnType<typeof getAlbumsShareShareLink>, TError = AxiosError<AlbumErrorResponse>>(
 shareLink: string, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getAlbumsShareShareLink>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetAlbumsShareShareLinkQueryKey(shareLink);

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getAlbumsShareShareLink>> = () => getAlbumsShareShareLink(shareLink, axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getAlbumsShareShareLink>, TError, TData>(queryKey, queryFn, {enabled: !!(shareLink), ...queryOptions})

  return {
    queryKey,
    ...query
  }
}


/**
 * Поиск альбомов по указанным тегам (требует аутентификации)
 * @summary Поиск альбомов по тегам
 */
export const postAlbumsSearchTags = (
    searchAlbumsByTagsDto: SearchAlbumsByTagsDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumResponse[]>> => {
    return axios.post(
      `/albums/search/tags`,
      searchAlbumsByTagsDto,options
    );
  }



    export const usePostAlbumsSearchTags = <TError = AxiosError<AlbumErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postAlbumsSearchTags>, TError,{data: SearchAlbumsByTagsDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postAlbumsSearchTags>, {data: SearchAlbumsByTagsDto}> = (props) => {
          const {data} = props || {};

          return  postAlbumsSearchTags(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postAlbumsSearchTags>, TError, {data: SearchAlbumsByTagsDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Установка фотографии в качестве обложки альбома (требует аутентификации)
 * @summary Установка обложки альбома
 */
export const putAlbumsCover = (
    setCoverPhotoDto: SetCoverPhotoDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumResponse>> => {
    return axios.put(
      `/albums/cover`,
      setCoverPhotoDto,options
    );
  }



    export const usePutAlbumsCover = <TError = AxiosError<AlbumErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof putAlbumsCover>, TError,{data: SetCoverPhotoDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof putAlbumsCover>, {data: SetCoverPhotoDto}> = (props) => {
          const {data} = props || {};

          return  putAlbumsCover(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof putAlbumsCover>, TError, {data: SetCoverPhotoDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Добавление нового тега к альбому (требует аутентификации)
 * @summary Добавление тега к альбому
 */
export const postAlbumsTag = (
    addTagDto: AddTagDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumResponse>> => {
    return axios.post(
      `/albums/tag`,
      addTagDto,options
    );
  }



    export const usePostAlbumsTag = <TError = AxiosError<AlbumErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postAlbumsTag>, TError,{data: AddTagDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postAlbumsTag>, {data: AddTagDto}> = (props) => {
          const {data} = props || {};

          return  postAlbumsTag(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postAlbumsTag>, TError, {data: AddTagDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Удаление тега из альбома (требует аутентификации)
 * @summary Удаление тега из альбома
 */
export const deleteAlbumsTag = (
    removeTagDto: RemoveTagDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumResponse>> => {
    return axios.delete(
      `/albums/tag`,{data:
      removeTagDto, ...options}
    );
  }



    export const useDeleteAlbumsTag = <TError = AxiosError<AlbumErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof deleteAlbumsTag>, TError,{data: RemoveTagDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof deleteAlbumsTag>, {data: RemoveTagDto}> = (props) => {
          const {data} = props || {};

          return  deleteAlbumsTag(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof deleteAlbumsTag>, TError, {data: RemoveTagDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Создаёт альбом в указанном подпроекте. Название (title) генерируется автоматически — "01", "02", "03" и т.д. по максимальному числовому title среди существующих альбомов подпроекта. Папка альбома создаётся на Яндекс.Диске (если настроен конфиг). Требует аутентификации.
 * @summary Создание нового альбома (чанка)
 */
export const postAlbums = (
    createAlbumDto: CreateAlbumDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumResponse>> => {
    return axios.post(
      `/albums`,
      createAlbumDto,options
    );
  }



    export const usePostAlbums = <TError = AxiosError<AlbumErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postAlbums>, TError,{data: CreateAlbumDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postAlbums>, {data: CreateAlbumDto}> = (props) => {
          const {data} = props || {};

          return  postAlbums(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postAlbums>, TError, {data: CreateAlbumDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Получение списка всех альбомов пользователя (требует аутентификации)
 * @summary Получение всех альбомов
 */
export const getAlbums = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumResponse[]>> => {
    return axios.get(
      `/albums`,options
    );
  }


export const getGetAlbumsQueryKey = () => [`/albums`];

    
export const useGetAlbums = <TData = AsyncReturnType<typeof getAlbums>, TError = AxiosError<AlbumErrorResponse>>(
  options?: { query?:UseQueryOptions<AsyncReturnType<typeof getAlbums>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetAlbumsQueryKey();

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getAlbums>> = () => getAlbums(axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getAlbums>, TError, TData>(queryKey, queryFn, queryOptions)

  return {
    queryKey,
    ...query
  }
}


/**
 * Получение информации об альбоме по его идентификатору (требует аутентификации)
 * @summary Получение альбома по ID
 */
export const getAlbumsId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumResponse>> => {
    return axios.get(
      `/albums/${id}`,options
    );
  }


export const getGetAlbumsIdQueryKey = (id: string,) => [`/albums/${id}`];

    
export const useGetAlbumsId = <TData = AsyncReturnType<typeof getAlbumsId>, TError = AxiosError<AlbumErrorResponse>>(
 id: string, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getAlbumsId>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetAlbumsIdQueryKey(id);

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getAlbumsId>> = () => getAlbumsId(id, axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getAlbumsId>, TError, TData>(queryKey, queryFn, {enabled: !!(id), ...queryOptions})

  return {
    queryKey,
    ...query
  }
}


/**
 * Обновление информации об альбоме (требует аутентификации)
 * @summary Обновление альбома
 */
export const putAlbumsId = (
    id: string,
    updateAlbumDto: UpdateAlbumDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumResponse>> => {
    return axios.put(
      `/albums/${id}`,
      updateAlbumDto,options
    );
  }



    export const usePutAlbumsId = <TError = AxiosError<AlbumErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof putAlbumsId>, TError,{id: string;data: UpdateAlbumDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof putAlbumsId>, {id: string;data: UpdateAlbumDto}> = (props) => {
          const {id,data} = props || {};

          return  putAlbumsId(id,data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof putAlbumsId>, TError, {id: string;data: UpdateAlbumDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Удаление альбома по его идентификатору (требует аутентификации)
 * @summary Удаление альбома
 */
export const deleteAlbumsId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumDeleteResponse>> => {
    return axios.delete(
      `/albums/${id}`,options
    );
  }



    export const useDeleteAlbumsId = <TError = AxiosError<AlbumErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof deleteAlbumsId>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof deleteAlbumsId>, {id: string}> = (props) => {
          const {id} = props || {};

          return  deleteAlbumsId(id,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof deleteAlbumsId>, TError, {id: string}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Установка статуса processed для альбома (требует аутентификации)
 * @summary Установка статуса обработки альбома
 */
export const putAlbumsProcessed = (
    setProcessedDto: SetProcessedDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlbumResponse>> => {
    return axios.put(
      `/albums/processed`,
      setProcessedDto,options
    );
  }



    export const usePutAlbumsProcessed = <TError = AxiosError<AlbumErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof putAlbumsProcessed>, TError,{data: SetProcessedDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof putAlbumsProcessed>, {data: SetProcessedDto}> = (props) => {
          const {data} = props || {};

          return  putAlbumsProcessed(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof putAlbumsProcessed>, TError, {data: SetProcessedDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Загружает изображение в S3 хранилище и создает запись в базе данных
 * @summary Загрузка фото в альбом
 */
export const postPhotosUpload = (
    postPhotosUploadBody: PostPhotosUploadBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UploadPhotoResponse>> => {const formData = new FormData();
formData.append('photo', postPhotosUploadBody.photo)
formData.append('albumId', postPhotosUploadBody.albumId)
if(postPhotosUploadBody.tags !== undefined) {
 formData.append('tags', postPhotosUploadBody.tags)
 }

    return axios.post(
      `/photos/upload`,
      formData,options
    );
  }



    export const usePostPhotosUpload = <TError = AxiosError<PhotoErrorResponse | void>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postPhotosUpload>, TError,{data: PostPhotosUploadBody}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postPhotosUpload>, {data: PostPhotosUploadBody}> = (props) => {
          const {data} = props || {};

          return  postPhotosUpload(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postPhotosUpload>, TError, {data: PostPhotosUploadBody}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Возвращает информацию о фото по его уникальному идентификатору.

**Версии фотографий:**
- `current` - текущие версии (могут изменяться при улучшении)
- `default` - версии по умолчанию (неизменны, для отката изменений)

 * @summary Получение фото по ID
 */
export const getPhotosId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Photo>> => {
    return axios.get(
      `/photos/${id}`,options
    );
  }


export const getGetPhotosIdQueryKey = (id: string,) => [`/photos/${id}`];

    
export const useGetPhotosId = <TData = AsyncReturnType<typeof getPhotosId>, TError = AxiosError<void | PhotoErrorResponse>>(
 id: string, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getPhotosId>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetPhotosIdQueryKey(id);

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getPhotosId>> = () => getPhotosId(id, axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getPhotosId>, TError, TData>(queryKey, queryFn, {enabled: !!(id), ...queryOptions})

  return {
    queryKey,
    ...query
  }
}


/**
 * Обновляет метаданные фото (имя файла, теги, статус обложки)
 * @summary Обновление метаданных фото
 */
export const putPhotosId = (
    id: string,
    updatePhotoRequest: UpdatePhotoRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Photo>> => {
    return axios.put(
      `/photos/${id}`,
      updatePhotoRequest,options
    );
  }



    export const usePutPhotosId = <TError = AxiosError<PhotoErrorResponse | void>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof putPhotosId>, TError,{id: string;data: UpdatePhotoRequest}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof putPhotosId>, {id: string;data: UpdatePhotoRequest}> = (props) => {
          const {id,data} = props || {};

          return  putPhotosId(id,data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof putPhotosId>, TError, {id: string;data: UpdatePhotoRequest}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Удаляет фото из базы данных и S3 хранилища
 * @summary Удаление фото
 */
export const deletePhotosId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeletePhotoResponse>> => {
    return axios.delete(
      `/photos/${id}`,options
    );
  }



    export const useDeletePhotosId = <TError = AxiosError<void | PhotoErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof deletePhotosId>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof deletePhotosId>, {id: string}> = (props) => {
          const {id} = props || {};

          return  deletePhotosId(id,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof deletePhotosId>, TError, {id: string}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Возвращает список всех фото в указанном альбоме
 * @summary Получение фото альбома
 */
export const getPhotosAlbumAlbumId = (
    albumId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PhotoListResponse>> => {
    return axios.get(
      `/photos/album/${albumId}`,options
    );
  }


export const getGetPhotosAlbumAlbumIdQueryKey = (albumId: string,) => [`/photos/album/${albumId}`];

    
export const useGetPhotosAlbumAlbumId = <TData = AsyncReturnType<typeof getPhotosAlbumAlbumId>, TError = AxiosError<void>>(
 albumId: string, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getPhotosAlbumAlbumId>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetPhotosAlbumAlbumIdQueryKey(albumId);

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getPhotosAlbumAlbumId>> = () => getPhotosAlbumAlbumId(albumId, axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getPhotosAlbumAlbumId>, TError, TData>(queryKey, queryFn, {enabled: !!(albumId), ...queryOptions})

  return {
    queryKey,
    ...query
  }
}


/**
 * Устанавливает указанное фото как обложку альбома
 * @summary Установка обложки альбома
 */
export const putPhotosIdSetcover = (
    id: string,
    setCoverRequest: SetCoverRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Photo>> => {
    return axios.put(
      `/photos/${id}/set-cover`,
      setCoverRequest,options
    );
  }



    export const usePutPhotosIdSetcover = <TError = AxiosError<PhotoErrorResponse | void>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof putPhotosIdSetcover>, TError,{id: string;data: SetCoverRequest}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof putPhotosIdSetcover>, {id: string;data: SetCoverRequest}> = (props) => {
          const {id,data} = props || {};

          return  putPhotosIdSetcover(id,data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof putPhotosIdSetcover>, TError, {id: string;data: SetCoverRequest}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Агрегирует записи `processing` (model, at, cost, currency).
В рублях: currency=RUB без конвертации; иначе cost в USD × курс GET /settings/usd-rub.
Ровно один параметр области: `projectId` (филиал), `subprojectId` или `albumId`.
Период: либо `month=YYYY-MM` (UTC), либо пара `from` и/или `to` (ISO 8601).

 * @summary Отчёт по затратам на обработку фото (журнал Replicate)
 */
export const getPhotosProcessingusage = (
    params?: GetPhotosProcessingusageParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.get(
      `/photos/processing-usage`,{
        params,
    ...options}
    );
  }


export const getGetPhotosProcessingusageQueryKey = (params?: GetPhotosProcessingusageParams,) => [`/photos/processing-usage`, ...(params ? [params]: [])];

    
export const useGetPhotosProcessingusage = <TData = AsyncReturnType<typeof getPhotosProcessingusage>, TError = AxiosError<unknown>>(
 params?: GetPhotosProcessingusageParams, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getPhotosProcessingusage>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetPhotosProcessingusageQueryKey(params);

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getPhotosProcessingusage>> = () => getPhotosProcessingusage(params, axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getPhotosProcessingusage>, TError, TData>(queryKey, queryFn, queryOptions)

  return {
    queryKey,
    ...query
  }
}


/**
 * Суммирует `processing` по проекту: RUB без конвертации, USD × курс из appsettings.
Четыре целых числа (рубли вверх): всё время; текущий календарный месяц / неделя / день (UTC).

 * @summary Сводка затрат Replicate по проекту (филиалу)
 */
export const getPhotosProcessingusageSummary = (
    params?: GetPhotosProcessingusageSummaryParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.get(
      `/photos/processing-usage/summary`,{
        params,
    ...options}
    );
  }


export const getGetPhotosProcessingusageSummaryQueryKey = (params?: GetPhotosProcessingusageSummaryParams,) => [`/photos/processing-usage/summary`, ...(params ? [params]: [])];

    
export const useGetPhotosProcessingusageSummary = <TData = AsyncReturnType<typeof getPhotosProcessingusageSummary>, TError = AxiosError<unknown>>(
 params?: GetPhotosProcessingusageSummaryParams, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getPhotosProcessingusageSummary>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetPhotosProcessingusageSummaryQueryKey(params);

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getPhotosProcessingusageSummary>> = () => getPhotosProcessingusageSummary(params, axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getPhotosProcessingusageSummary>, TError, TData>(queryKey, queryFn, queryOptions)

  return {
    queryKey,
    ...query
  }
}


/**
 * Добавляет фотографии в очередь для улучшения через GFPGAN.

После улучшения поле `current` обновляется новыми версиями, а `default` остается неизменным.
Это позволяет откатить изменения, скопировав `default` в `current`.

 * @summary Улучшение фотографий
 */
export const postPhotosImprovement = (
    postPhotosImprovementBody: PostPhotosImprovementBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostPhotosImprovement200>> => {
    return axios.post(
      `/photos/improvement`,
      postPhotosImprovementBody,options
    );
  }



    export const usePostPhotosImprovement = <TError = AxiosError<void>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postPhotosImprovement>, TError,{data: PostPhotosImprovementBody}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postPhotosImprovement>, {data: PostPhotosImprovementBody}> = (props) => {
          const {data} = props || {};

          return  postPhotosImprovement(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postPhotosImprovement>, TError, {data: PostPhotosImprovementBody}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Улучшение фотографии с использованием пользовательского промпта
 * @summary Кастомное улучшение фотографии
 */
export const postPhotosImprovementcustom = (
    postPhotosImprovementcustomBody: PostPhotosImprovementcustomBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostPhotosImprovementcustom200>> => {
    return axios.post(
      `/photos/improvement-custom`,
      postPhotosImprovementcustomBody,options
    );
  }



    export const usePostPhotosImprovementcustom = <TError = AxiosError<PhotoErrorResponse | void>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postPhotosImprovementcustom>, TError,{data: PostPhotosImprovementcustomBody}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postPhotosImprovementcustom>, {data: PostPhotosImprovementcustomBody}> = (props) => {
          const {data} = props || {};

          return  postPhotosImprovementcustom(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postPhotosImprovementcustom>, TError, {data: PostPhotosImprovementcustomBody}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Добавляет фото в очередь на обработку через flux-pro с переданным промптом.
Промпт на фронте берётся из default промпта или из выбранной версии history.
После обработки обновляется current, default остаётся неизменным.

 * @summary Наложение фона (обработка через flux-pro с промптом)
 */
export const postPhotosAddlayer = (
    postPhotosAddlayerBody: PostPhotosAddlayerBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostPhotosAddlayer200>> => {
    return axios.post(
      `/photos/addlayer`,
      postPhotosAddlayerBody,options
    );
  }



    export const usePostPhotosAddlayer = <TError = AxiosError<void>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postPhotosAddlayer>, TError,{data: PostPhotosAddlayerBody}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postPhotosAddlayer>, {data: PostPhotosAddlayerBody}> = (props) => {
          const {data} = props || {};

          return  postPhotosAddlayer(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postPhotosAddlayer>, TError, {data: PostPhotosAddlayerBody}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Восстанавливает значения из `default` в `current` и удаляет файлы из бакета,
которые были в `current`, но отсутствуют в `default`.

Это позволяет откатить изменения, сделанные улучшайзером.

 * @summary Откат изменений фото к версиям по умолчанию
 */
export const postPhotosIdRevert = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Photo>> => {
    return axios.post(
      `/photos/${id}/revert`,undefined,options
    );
  }



    export const usePostPhotosIdRevert = <TError = AxiosError<void | PhotoErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postPhotosIdRevert>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postPhotosIdRevert>, {id: string}> = (props) => {
          const {id} = props || {};

          return  postPhotosIdRevert(id,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postPhotosIdRevert>, TError, {id: string}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Отправляет фотографию на оценку нейросетью.
В данный момент логирует photo ID. Позже будет подключена нейросеть для оценки фото по промпту.
Оценка от нейросети будет сохранена в поле rating фотографии.

 * @summary Оценка фотографии
 */
export const postPhotosRating = (
    ratingPhotoRequest: RatingPhotoRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RatingPhotoResponse>> => {
    return axios.post(
      `/photos/rating`,
      ratingPhotoRequest,options
    );
  }



    export const usePostPhotosRating = <TError = AxiosError<PhotoErrorResponse | void>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postPhotosRating>, TError,{data: RatingPhotoRequest}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postPhotosRating>, {data: RatingPhotoRequest}> = (props) => {
          const {data} = props || {};

          return  postPhotosRating(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postPhotosRating>, TError, {data: RatingPhotoRequest}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Принимает набор дескрипторов и возвращает список фотографий, у которых найдено совпадение
 * @summary Сравнение дескрипторов лица с сохраненными образцами
 */
export const postDescriptors = (
    descriptorMatchRequest: DescriptorMatchRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DescriptorMatchResponse>> => {
    return axios.post(
      `/descriptors`,
      descriptorMatchRequest,options
    );
  }



    export const usePostDescriptors = <TError = AxiosError<void>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postDescriptors>, TError,{data: DescriptorMatchRequest}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postDescriptors>, {data: DescriptorMatchRequest}> = (props) => {
          const {data} = props || {};

          return  postDescriptors(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postDescriptors>, TError, {data: DescriptorMatchRequest}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Принимает «маску» — массив из 2-10 дескрипторов одного и того же лица в разных ракурсах
(фас + полупрофили), и возвращает список фотографий с найденным совпадением.
Скоуп всегда ограничен сегодняшним днём и филиалами авторизованного пользователя.

 * @summary Сравнение маски лица (набора ракурсов) с сохранёнными дескрипторами
 */
export const postDescriptorsMask = (
    descriptorMaskMatchRequest: DescriptorMaskMatchRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DescriptorMatchResponse>> => {
    return axios.post(
      `/descriptors/mask`,
      descriptorMaskMatchRequest,options
    );
  }



    export const usePostDescriptorsMask = <TError = AxiosError<void>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postDescriptorsMask>, TError,{data: DescriptorMaskMatchRequest}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postDescriptorsMask>, {data: DescriptorMaskMatchRequest}> = (props) => {
          const {data} = props || {};

          return  postDescriptorsMask(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postDescriptorsMask>, TError, {data: DescriptorMaskMatchRequest}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Создаёт промпт; текст в body на русском, перевод в EN через GigaChat сохраняется в body, default и history[0] (ru — исходный русский).
 * @summary Создание нового промпта
 */
export const postPrompts = (
    createPromptRequest: CreatePromptRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PromptResponse>> => {
    return axios.post(
      `/prompts`,
      createPromptRequest,options
    );
  }



    export const usePostPrompts = <TError = AxiosError<PromptErrorResponse | void>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postPrompts>, TError,{data: CreatePromptRequest}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postPrompts>, {data: CreatePromptRequest}> = (props) => {
          const {data} = props || {};

          return  postPrompts(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postPrompts>, TError, {data: CreatePromptRequest}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Возвращает список всех промптов, отсортированных по дате создания (новые первыми)
 * @summary Получение списка всех промптов
 */
export const getPrompts = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PromptResponse[]>> => {
    return axios.get(
      `/prompts`,options
    );
  }


export const getGetPromptsQueryKey = () => [`/prompts`];

    
export const useGetPrompts = <TData = AsyncReturnType<typeof getPrompts>, TError = AxiosError<void>>(
  options?: { query?:UseQueryOptions<AsyncReturnType<typeof getPrompts>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetPromptsQueryKey();

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getPrompts>> = () => getPrompts(axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getPrompts>, TError, TData>(queryKey, queryFn, queryOptions)

  return {
    queryKey,
    ...query
  }
}


/**
 * Возвращает информацию о промпте по его уникальному идентификатору
 * @summary Получение промпта по ID
 */
export const getPromptsId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PromptResponse>> => {
    return axios.get(
      `/prompts/${id}`,options
    );
  }


export const getGetPromptsIdQueryKey = (id: string,) => [`/prompts/${id}`];

    
export const useGetPromptsId = <TData = AsyncReturnType<typeof getPromptsId>, TError = AxiosError<void | PromptErrorResponse>>(
 id: string, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getPromptsId>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetPromptsIdQueryKey(id);

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getPromptsId>> = () => getPromptsId(id, axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getPromptsId>, TError, TData>(queryKey, queryFn, {enabled: !!(id), ...queryOptions})

  return {
    queryKey,
    ...query
  }
}


/**
 * Обновляет промпт; body и history[].ru с фронта на русском, английский promptBody/body подставляется после перевода. default не меняется.
 * @summary Обновление промпта
 */
export const putPromptsId = (
    id: string,
    updatePromptRequest: UpdatePromptRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PromptResponse>> => {
    return axios.put(
      `/prompts/${id}`,
      updatePromptRequest,options
    );
  }



    export const usePutPromptsId = <TError = AxiosError<void | PromptErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof putPromptsId>, TError,{id: string;data: UpdatePromptRequest}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof putPromptsId>, {id: string;data: UpdatePromptRequest}> = (props) => {
          const {id,data} = props || {};

          return  putPromptsId(id,data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof putPromptsId>, TError, {id: string;data: UpdatePromptRequest}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Удаляет промпт по его уникальному идентификатору
 * @summary Удаление промпта
 */
export const deletePromptsId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.delete(
      `/prompts/${id}`,options
    );
  }



    export const useDeletePromptsId = <TError = AxiosError<PromptErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof deletePromptsId>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof deletePromptsId>, {id: string}> = (props) => {
          const {id} = props || {};

          return  deletePromptsId(id,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof deletePromptsId>, TError, {id: string}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Создает новую AI модель с указанным названием и описанием
 * @summary Создание новой AI модели
 */
export const postAimodels = (
    createAimodelRequest: CreateAimodelRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AimodelResponse>> => {
    return axios.post(
      `/aimodels`,
      createAimodelRequest,options
    );
  }



    export const usePostAimodels = <TError = AxiosError<AimodelErrorResponse | void>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postAimodels>, TError,{data: CreateAimodelRequest}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postAimodels>, {data: CreateAimodelRequest}> = (props) => {
          const {data} = props || {};

          return  postAimodels(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postAimodels>, TError, {data: CreateAimodelRequest}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Возвращает список всех AI моделей, отсортированных по дате создания (новые первыми)
 * @summary Получение списка всех AI моделей
 */
export const getAimodels = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AimodelResponse[]>> => {
    return axios.get(
      `/aimodels`,options
    );
  }


export const getGetAimodelsQueryKey = () => [`/aimodels`];

    
export const useGetAimodels = <TData = AsyncReturnType<typeof getAimodels>, TError = AxiosError<void>>(
  options?: { query?:UseQueryOptions<AsyncReturnType<typeof getAimodels>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetAimodelsQueryKey();

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getAimodels>> = () => getAimodels(axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getAimodels>, TError, TData>(queryKey, queryFn, queryOptions)

  return {
    queryKey,
    ...query
  }
}


/**
 * Удаляет AI модель по ее уникальному идентификатору
 * @summary Удаление AI модели
 */
export const deleteAimodelsId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.delete(
      `/aimodels/${id}`,options
    );
  }



    export const useDeleteAimodelsId = <TError = AxiosError<AimodelErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof deleteAimodelsId>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof deleteAimodelsId>, {id: string}> = (props) => {
          const {id} = props || {};

          return  deleteAimodelsId(id,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof deleteAimodelsId>, TError, {id: string}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Создает новую камеру с указанными параметрами
 * @summary Создание новой камеры
 */
export const postCameras = (
    postCamerasBody: PostCamerasBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostCameras201>> => {
    return axios.post(
      `/cameras`,
      postCamerasBody,options
    );
  }



    export const usePostCameras = <TError = AxiosError<void>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postCameras>, TError,{data: PostCamerasBody}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postCameras>, {data: PostCamerasBody}> = (props) => {
          const {data} = props || {};

          return  postCameras(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postCameras>, TError, {data: PostCamerasBody}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Возвращает список всех камер, отсортированных по дате создания (новые первыми)
 * @summary Получение списка всех камер
 */
export const getCameras = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetCameras200Item[]>> => {
    return axios.get(
      `/cameras`,options
    );
  }


export const getGetCamerasQueryKey = () => [`/cameras`];

    
export const useGetCameras = <TData = AsyncReturnType<typeof getCameras>, TError = AxiosError<void>>(
  options?: { query?:UseQueryOptions<AsyncReturnType<typeof getCameras>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetCamerasQueryKey();

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getCameras>> = () => getCameras(axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getCameras>, TError, TData>(queryKey, queryFn, queryOptions)

  return {
    queryKey,
    ...query
  }
}


/**
 * Обновляет данные камеры по ее идентификатору. cameraId нельзя изменять после создания.
 * @summary Обновление камеры
 */
export const putCamerasId = (
    id: string,
    putCamerasIdBody: PutCamerasIdBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PutCamerasId200>> => {
    return axios.put(
      `/cameras/${id}`,
      putCamerasIdBody,options
    );
  }



    export const usePutCamerasId = <TError = AxiosError<void>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof putCamerasId>, TError,{id: string;data: PutCamerasIdBody}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof putCamerasId>, {id: string;data: PutCamerasIdBody}> = (props) => {
          const {id,data} = props || {};

          return  putCamerasId(id,data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof putCamerasId>, TError, {id: string;data: PutCamerasIdBody}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Удаляет камеру по ее уникальному идентификатору
 * @summary Удаление камеры
 */
export const deleteCamerasId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.delete(
      `/cameras/${id}`,options
    );
  }



    export const useDeleteCamerasId = <TError = AxiosError<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof deleteCamerasId>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof deleteCamerasId>, {id: string}> = (props) => {
          const {id} = props || {};

          return  deleteCamerasId(id,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof deleteCamerasId>, TError, {id: string}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Возвращает конфиг для указанного проекта. Токен в ответе маскируется. Доступ только для ролей owner и agency.
 * @summary Получить конфигурацию Яндекс.Диска по проекту
 */
export const getYandexdiskProjectProjectId = (
    projectId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<YandexDiskConfigResponse>> => {
    return axios.get(
      `/yandex-disk/project/${projectId}`,options
    );
  }


export const getGetYandexdiskProjectProjectIdQueryKey = (projectId: string,) => [`/yandex-disk/project/${projectId}`];

    
export const useGetYandexdiskProjectProjectId = <TData = AsyncReturnType<typeof getYandexdiskProjectProjectId>, TError = AxiosError<void>>(
 projectId: string, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getYandexdiskProjectProjectId>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetYandexdiskProjectProjectIdQueryKey(projectId);

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getYandexdiskProjectProjectId>> = () => getYandexdiskProjectProjectId(projectId, axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getYandexdiskProjectProjectId>, TError, TData>(queryKey, queryFn, {enabled: !!(projectId), ...queryOptions})

  return {
    queryKey,
    ...query
  }
}


/**
 * Создаёт конфиг, если его нет, или обновляет существующий. Доступ только для ролей owner и agency.
 * @summary Создать или обновить конфигурацию Яндекс.Диска для проекта
 */
export const putYandexdiskProjectProjectId = (
    projectId: string,
    createOrUpdateYandexDiskConfigDto: CreateOrUpdateYandexDiskConfigDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<YandexDiskConfigResponse>> => {
    return axios.put(
      `/yandex-disk/project/${projectId}`,
      createOrUpdateYandexDiskConfigDto,options
    );
  }



    export const usePutYandexdiskProjectProjectId = <TError = AxiosError<void>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof putYandexdiskProjectProjectId>, TError,{projectId: string;data: CreateOrUpdateYandexDiskConfigDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof putYandexdiskProjectProjectId>, {projectId: string;data: CreateOrUpdateYandexDiskConfigDto}> = (props) => {
          const {projectId,data} = props || {};

          return  putYandexdiskProjectProjectId(projectId,data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof putYandexdiskProjectProjectId>, TError, {projectId: string;data: CreateOrUpdateYandexDiskConfigDto}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Удаляет привязку Яндекс.Диска к проекту. Доступ только для ролей owner и agency.
 * @summary Удалить конфигурацию Яндекс.Диска для проекта
 */
export const deleteYandexdiskProjectProjectId = (
    projectId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<YandexDiskDeleteResponse>> => {
    return axios.delete(
      `/yandex-disk/project/${projectId}`,options
    );
  }



    export const useDeleteYandexdiskProjectProjectId = <TError = AxiosError<void>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof deleteYandexdiskProjectProjectId>, TError,{projectId: string}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof deleteYandexdiskProjectProjectId>, {projectId: string}> = (props) => {
          const {projectId} = props || {};

          return  deleteYandexdiskProjectProjectId(projectId,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof deleteYandexdiskProjectProjectId>, TError, {projectId: string}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Читает состояние Яндекс.Диска в рамках структуры проекта и применяет изменения в WANMAX
(фото default/current + каталоги subproject/album). Мутации `project` из Я.Диска не выполняются.

 * @summary Запустить обратную синхронизацию Яндекс.Диска -> WANMAX
 */
export const postYandexdiskSyncProjectProjectId = (
    projectId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostYandexdiskSyncProjectProjectId200>> => {
    return axios.post(
      `/yandex-disk/sync/project/${projectId}`,undefined,options
    );
  }



    export const usePostYandexdiskSyncProjectProjectId = <TError = AxiosError<void>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postYandexdiskSyncProjectProjectId>, TError,{projectId: string}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postYandexdiskSyncProjectProjectId>, {projectId: string}> = (props) => {
          const {projectId} = props || {};

          return  postYandexdiskSyncProjectProjectId(projectId,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postYandexdiskSyncProjectProjectId>, TError, {projectId: string}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Возвращает сохранённый в БД курс USD/RUB, дату последнего обновления и источник
(`manual` — выставлено вручную через PUT, `tinkoff` — подтянуто с Тинькофф C2CTransfers.sell).

 * @summary Текущий курс USD→RUB из БД
 */
export const getSettingsUsdrub = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.get(
      `/settings/usd-rub`,options
    );
  }


export const getGetSettingsUsdrubQueryKey = () => [`/settings/usd-rub`];

    
export const useGetSettingsUsdrub = <TData = AsyncReturnType<typeof getSettingsUsdrub>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<AsyncReturnType<typeof getSettingsUsdrub>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetSettingsUsdrubQueryKey();

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getSettingsUsdrub>> = () => getSettingsUsdrub(axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getSettingsUsdrub>, TError, TData>(queryKey, queryFn, queryOptions)

  return {
    queryKey,
    ...query
  }
}


/**
 * Разовая инициализация; ежедневное обновление делает cron из Тинькофф (C2CTransfers.sell).
 * @summary Задать или обновить курс USD→RUB вручную
 */
export const putSettingsUsdrub = (
    putSettingsUsdrubBody: PutSettingsUsdrubBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.put(
      `/settings/usd-rub`,
      putSettingsUsdrubBody,options
    );
  }



    export const usePutSettingsUsdrub = <TError = AxiosError<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof putSettingsUsdrub>, TError,{data: PutSettingsUsdrubBody}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof putSettingsUsdrub>, {data: PutSettingsUsdrubBody}> = (props) => {
          const {data} = props || {};

          return  putSettingsUsdrub(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof putSettingsUsdrub>, TError, {data: PutSettingsUsdrubBody}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * Делает тот же запрос к публичному API Тинькофф, что и ночной cron, — берёт курс продажи
(`payload.rates[].sell` с `category: "C2CTransfers"`, `from=USD`, `to=RUB`).
Именно по такому курсу банк фактически продаёт валюту клиенту, а не по официальному курсу ЦБ.
Если API недоступен или ответ некорректен — БД не меняется, ответ 502.
Автообновление по расписанию остаётся в 01:00 МСК.

 * @summary Подтянуть курс USD/RUB с Тинькофф (C2CTransfers.sell)
 */
export const postSettingsUsdrubRefresh = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.post(
      `/settings/usd-rub/refresh`,undefined,options
    );
  }



    export const usePostSettingsUsdrubRefresh = <TError = AxiosError<unknown>,
    TVariables = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postSettingsUsdrubRefresh>, TError,TVariables, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postSettingsUsdrubRefresh>, TVariables> = () => {
          return  postSettingsUsdrubRefresh(axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postSettingsUsdrubRefresh>, TError, TVariables, TContext>(mutationFn, mutationOptions)
    }
    
