/**
 * Generated by orval v6.6.2 🍺
 * Do not edit manually.
 * A7 Backend API
 * API документация для A7 Backend
 * OpenAPI spec version: 1.0.0
 */
import axios,{
  AxiosRequestConfig,
  AxiosResponse,
  AxiosError
} from 'axios'
import {
  useQuery,
  useMutation,
  UseQueryOptions,
  UseMutationOptions,
  QueryFunction,
  MutationFunction,
  UseQueryResult,
  QueryKey
} from 'react-query'
import type {
  AuthResponse,
  PostApiAuthRegisterBody,
  LoginRequest,
  GetApiAuthProfile200,
  PostApiAuthRefresh200,
  ErrorResponse,
  PostApiAuthRefreshBody,
  PostApiAuthLogout200,
  GetApiUsers200,
  PostApiUsers201,
  PostApiUsersBody,
  GetApiUsersId200,
  PutApiUsersId200,
  PutApiUsersIdBody,
  DeleteApiUsersId200
} from './model'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AsyncReturnType<
T extends (...args: any) => Promise<any>
> = T extends (...args: any) => Promise<infer R> ? R : any;


/**
 * @summary Регистрация нового пользователя
 */
export const postApiAuthRegister = (
    postApiAuthRegisterBody: PostApiAuthRegisterBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AuthResponse>> => {
    return axios.post(
      `/api/auth/register`,
      postApiAuthRegisterBody,options
    );
  }



    export const usePostApiAuthRegister = <TError = AxiosError<void>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postApiAuthRegister>, TError,{data: PostApiAuthRegisterBody}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postApiAuthRegister>, {data: PostApiAuthRegisterBody}> = (props) => {
          const {data} = props || {};

          return  postApiAuthRegister(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postApiAuthRegister>, TError, {data: PostApiAuthRegisterBody}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * @summary Вход пользователя
 */
export const postApiAuthLogin = (
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AuthResponse>> => {
    return axios.post(
      `/api/auth/login`,
      loginRequest,options
    );
  }



    export const usePostApiAuthLogin = <TError = AxiosError<void>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postApiAuthLogin>, TError,{data: LoginRequest}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postApiAuthLogin>, {data: LoginRequest}> = (props) => {
          const {data} = props || {};

          return  postApiAuthLogin(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postApiAuthLogin>, TError, {data: LoginRequest}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * @summary Получение профиля текущего пользователя
 */
export const getApiAuthProfile = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetApiAuthProfile200>> => {
    return axios.get(
      `/api/auth/profile`,options
    );
  }


export const getGetApiAuthProfileQueryKey = () => [`/api/auth/profile`];

    
export const useGetApiAuthProfile = <TData = AsyncReturnType<typeof getApiAuthProfile>, TError = AxiosError<void>>(
  options?: { query?:UseQueryOptions<AsyncReturnType<typeof getApiAuthProfile>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetApiAuthProfileQueryKey();

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getApiAuthProfile>> = () => getApiAuthProfile(axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getApiAuthProfile>, TError, TData>(queryKey, queryFn, queryOptions)

  return {
    queryKey,
    ...query
  }
}


/**
 * @summary Обновление access token
 */
export const postApiAuthRefresh = (
    postApiAuthRefreshBody: PostApiAuthRefreshBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostApiAuthRefresh200>> => {
    return axios.post(
      `/api/auth/refresh`,
      postApiAuthRefreshBody,options
    );
  }



    export const usePostApiAuthRefresh = <TError = AxiosError<ErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postApiAuthRefresh>, TError,{data: PostApiAuthRefreshBody}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postApiAuthRefresh>, {data: PostApiAuthRefreshBody}> = (props) => {
          const {data} = props || {};

          return  postApiAuthRefresh(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postApiAuthRefresh>, TError, {data: PostApiAuthRefreshBody}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * @summary Выход пользователя
 */
export const postApiAuthLogout = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostApiAuthLogout200>> => {
    return axios.post(
      `/api/auth/logout`,undefined,options
    );
  }



    export const usePostApiAuthLogout = <TError = AxiosError<ErrorResponse>,
    TVariables = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postApiAuthLogout>, TError,TVariables, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postApiAuthLogout>, TVariables> = () => {
          ;

          return  postApiAuthLogout(axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postApiAuthLogout>, TError, TVariables, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * @summary Получение всех пользователей
 */
export const getApiUsers = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetApiUsers200>> => {
    return axios.get(
      `/api/users`,options
    );
  }


export const getGetApiUsersQueryKey = () => [`/api/users`];

    
export const useGetApiUsers = <TData = AsyncReturnType<typeof getApiUsers>, TError = AxiosError<ErrorResponse>>(
  options?: { query?:UseQueryOptions<AsyncReturnType<typeof getApiUsers>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetApiUsersQueryKey();

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getApiUsers>> = () => getApiUsers(axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getApiUsers>, TError, TData>(queryKey, queryFn, queryOptions)

  return {
    queryKey,
    ...query
  }
}


/**
 * @summary Создание нового пользователя
 */
export const postApiUsers = (
    postApiUsersBody: PostApiUsersBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostApiUsers201>> => {
    return axios.post(
      `/api/users`,
      postApiUsersBody,options
    );
  }



    export const usePostApiUsers = <TError = AxiosError<ErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postApiUsers>, TError,{data: PostApiUsersBody}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postApiUsers>, {data: PostApiUsersBody}> = (props) => {
          const {data} = props || {};

          return  postApiUsers(data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postApiUsers>, TError, {data: PostApiUsersBody}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * @summary Получение пользователя по ID
 */
export const getApiUsersId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetApiUsersId200>> => {
    return axios.get(
      `/api/users/${id}`,options
    );
  }


export const getGetApiUsersIdQueryKey = (id: string,) => [`/api/users/${id}`];

    
export const useGetApiUsersId = <TData = AsyncReturnType<typeof getApiUsersId>, TError = AxiosError<void>>(
 id: string, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getApiUsersId>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetApiUsersIdQueryKey(id);

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getApiUsersId>> = () => getApiUsersId(id, axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getApiUsersId>, TError, TData>(queryKey, queryFn, {enabled: !!(id), ...queryOptions})

  return {
    queryKey,
    ...query
  }
}


/**
 * @summary Обновление пользователя
 */
export const putApiUsersId = (
    id: string,
    putApiUsersIdBody: PutApiUsersIdBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PutApiUsersId200>> => {
    return axios.put(
      `/api/users/${id}`,
      putApiUsersIdBody,options
    );
  }



    export const usePutApiUsersId = <TError = AxiosError<ErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof putApiUsersId>, TError,{id: string;data: PutApiUsersIdBody}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof putApiUsersId>, {id: string;data: PutApiUsersIdBody}> = (props) => {
          const {id,data} = props || {};

          return  putApiUsersId(id,data,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof putApiUsersId>, TError, {id: string;data: PutApiUsersIdBody}, TContext>(mutationFn, mutationOptions)
    }
    
/**
 * @summary Удаление пользователя
 */
export const deleteApiUsersId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeleteApiUsersId200>> => {
    return axios.delete(
      `/api/users/${id}`,options
    );
  }



    export const useDeleteApiUsersId = <TError = AxiosError<ErrorResponse>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof deleteApiUsersId>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof deleteApiUsersId>, {id: string}> = (props) => {
          const {id} = props || {};

          return  deleteApiUsersId(id,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof deleteApiUsersId>, TError, {id: string}, TContext>(mutationFn, mutationOptions)
    }
    
